// GENERATED by pi-cache/scripts/sync-router-engine.mjs from services/leadingLine.ts.
// Do not edit here: change the app copy, then re-run the script (see pi-cache/src/services/inshoreRouter.ts).
/**
 * leadingLine — charted leading-line (transit) follower. The routing-stack
 * refinement that snaps a route onto the EXACT charted navigation_line where
 * it transits one, so the track follows correct vessel procedure: line up the
 * two leading marks and steer the transit. Runs AFTER the A* route + Fairlead.
 *
 * A leading line (OSM `seamark:type=navigation_line`, category=leading) is a
 * straight charted transit: two marks you keep aligned to stay mid-channel.
 * The engine's Pass 5b already ATTRACTS A* toward these lines (a ~150 m
 * preferred corridor); this module SNAPS the route onto the line itself, so
 * instead of "near the channel" you get "dead on the transit" — the way a
 * skipper actually steers a leading line.
 *
 * Self-contained pure functions over lat/lon (no engine import) so they can be
 * parity-tested in isolation — same pattern as fairlead.ts.
 */
import { readS57 } from './enc/types.js';

export interface LatLon {
    lat: number;
    lon: number;
}

/** A charted leading line = its polyline geometry (≥2 points). Leading lines
 *  are straight, but a multi-vertex transit is tolerated. */
export interface LeadingLine {
    pts: LatLon[];
}

/** Warning/review identity, deliberately separate from the legacy geometry-
 * only snapper. A navigation bearing is not automatically a sailing track. */
export interface ChartTrackLine extends LeadingLine {
    chartTrack: {
        id: string;
        label: string;
        kind: 'leading-line' | 'recommended-track';
        objectClass: 'RECTRC' | 'NAVLNE' | 'OSM_NAVLINE';
        category: number | 'leading';
        source?: string;
        sourceCell?: string;
        featureId?: string;
        name?: string;
        orientationDeg?: number;
        traffic?: number;
    };
}

/** Minimal GeoJSON-ish shape so this module needn't depend on @types/geojson. */
interface LineFeatureLike {
    geometry?: { type?: string; coordinates?: unknown } | null;
    properties?: Record<string, unknown> | null;
}

/** Metres between two lat/lon (local equirectangular — fine at channel scale). */
export function distM(a: LatLon, b: LatLon): number {
    const mPerLat = 110_540;
    const mPerLon = 111_320 * Math.cos((a.lat * Math.PI) / 180);
    return Math.hypot((b.lon - a.lon) * mPerLon, (b.lat - a.lat) * mPerLat);
}

/** Bearing (degrees, [0,360)) from a→b in local planar metres. */
function bearingDeg(a: LatLon, b: LatLon): number {
    const mPerLat = 110_540;
    const mPerLon = 111_320 * Math.cos((a.lat * Math.PI) / 180);
    const dx = (b.lon - a.lon) * mPerLon;
    const dy = (b.lat - a.lat) * mPerLat;
    let deg = (Math.atan2(dx, dy) * 180) / Math.PI;
    if (deg < 0) deg += 360;
    return deg;
}

/** Smallest angular difference (degrees) treating both as UNDIRECTED lines, so
 *  10° and 190° are 0° apart. Range [0,90]. */
function lineAngleDiffDeg(a: number, b: number): number {
    let d = Math.abs(a - b) % 180;
    if (d > 90) d = 180 - d;
    return d;
}

/** Project p onto segment a→b; closest point + its distance from p + param t∈[0,1]. */
function projectToSegment(p: LatLon, a: LatLon, b: LatLon): { point: LatLon; dist: number; t: number } {
    const mLat = 110_540;
    const mLon = 111_320 * Math.cos((a.lat * Math.PI) / 180);
    const bx = (b.lon - a.lon) * mLon;
    const by = (b.lat - a.lat) * mLat;
    const px = (p.lon - a.lon) * mLon;
    const py = (p.lat - a.lat) * mLat;
    const len2 = bx * bx + by * by;
    let t = len2 > 0 ? (px * bx + py * by) / len2 : 0;
    t = Math.max(0, Math.min(1, t));
    const point = { lat: a.lat + (b.lat - a.lat) * t, lon: a.lon + (b.lon - a.lon) * t };
    return { point, dist: distM(p, point), t };
}

/** Nearest point on a (multi-segment) line to p. Exported for the Route
 *  Tracer's off-the-lead check (services/routeTracer.ts). */
export function projectToLine(p: LatLon, line: LatLon[]): { point: LatLon; dist: number } {
    let best = { point: line[0], dist: Infinity };
    for (let i = 0; i < line.length - 1; i++) {
        const pr = projectToSegment(p, line[i], line[i + 1]);
        if (pr.dist < best.dist) best = { point: pr.point, dist: pr.dist };
    }
    return best;
}

/** Like projectToLine, but also returns WHICH segment [seg, seg+1] the projection
 *  landed on and the param t along it — so a snap can walk the line's OWN interior
 *  vertices between two projections instead of chording straight across them. */
function projectToLineIndexed(p: LatLon, line: LatLon[]): { point: LatLon; dist: number; seg: number; t: number } {
    let best = { point: line[0], dist: Infinity, seg: 0, t: 0 };
    for (let i = 0; i < line.length - 1; i++) {
        const pr = projectToSegment(p, line[i], line[i + 1]);
        if (pr.dist < best.dist) best = { point: pr.point, dist: pr.dist, seg: i, t: pr.t };
    }
    return best;
}

/** The sub-polyline of `line` from projection a to projection b, INCLUSIVE of every
 *  intermediate line vertex between them — so a curved recommended track is followed
 *  around its bends, not chorded across (which would cut the inside of the bend and
 *  pin the route to one bank). Returns [a.point, …interior…, b.point] in the route's
 *  travel direction. A straight line (no interior vertex between the projections)
 *  returns exactly [a.point, b.point] — identical to the old chord. */
function onLineSubPolyline(
    line: LatLon[],
    a: { point: LatLon; seg: number; t: number },
    b: { point: LatLon; seg: number; t: number },
): LatLon[] {
    const aBeforeB = a.seg < b.seg || (a.seg === b.seg && a.t <= b.t);
    const lo = aBeforeB ? a : b;
    const hi = aBeforeB ? b : a;
    const out: LatLon[] = [lo.point];
    for (let v = lo.seg + 1; v <= hi.seg; v++) out.push(line[v]);
    out.push(hi.point);
    const ordered = aBeforeB ? out : out.reverse();
    return ordered.filter((p, i) => i === 0 || distM(ordered[i - 1], p) > 1);
}

/** True if any point sampled ~every stepM along the polyline satisfies pred. */
export function anyAlong(pts: LatLon[], stepM: number, pred: (p: LatLon) => boolean): boolean {
    for (let i = 0; i < pts.length - 1; i++) {
        const a = pts[i];
        const b = pts[i + 1];
        const n = Math.max(1, Math.ceil(distM(a, b) / stepM));
        for (let k = 0; k <= n; k++) {
            const t = k / n;
            if (pred({ lat: a.lat + (b.lat - a.lat) * t, lon: a.lon + (b.lon - a.lon) * t })) return true;
        }
    }
    return false;
}

/** Total along-path length (metres) of poly[from..to] inclusive. */
function runLengthM(poly: LatLon[], from: number, to: number): number {
    let m = 0;
    for (let i = from; i < to; i++) m += distM(poly[i], poly[i + 1]);
    return m;
}

/**
 * Parse NAVLINE features (LineString/MultiLineString) into bare lead geometry.
 * This parser does NOT judge categories: chart NAVLNE of every CATNAV and OSM
 * lines alike come out as geometry. Callers that use the result as a lead must
 * pass the features through navLineLeads first (the merge, the engine entry,
 * the grid and the tracer all do), so clearing and transit lines never lead.
 */
export function parseLeadingLines(features: LineFeatureLike[]): LeadingLine[] {
    const out: LeadingLine[] = [];
    for (const f of features) {
        const g = f.geometry;
        if (!g || !Array.isArray(g.coordinates)) continue;
        const rings: number[][][] =
            g.type === 'LineString'
                ? [g.coordinates as number[][]]
                : g.type === 'MultiLineString'
                  ? (g.coordinates as number[][][])
                  : [];
        for (const coords of rings) {
            const pts: LatLon[] = coords
                .filter((c) => Array.isArray(c) && c.length >= 2 && Number.isFinite(c[0]) && Number.isFinite(c[1]))
                .map((c) => ({ lat: c[1], lon: c[0] }));
            if (pts.length >= 2) out.push({ pts });
        }
    }
    return out;
}

const singleCode = (value: unknown): number | undefined => {
    if (typeof value === 'number' && Number.isInteger(value)) return value;
    if (typeof value === 'string' && /^\d+$/.test(value.trim())) return Number(value);
    return undefined;
};

const shortText = (value: unknown): string | undefined =>
    typeof value === 'string' && value.trim() ? value.trim().slice(0, 160) : undefined;

/** The tracer merge adds provenance to copies, never to cached chart blobs. */
export function withChartTrackSource<T extends { properties?: Record<string, unknown> | null }>(
    feature: T,
    cellId: string,
): T {
    return { ...feature, properties: { ...feature.properties, _cellId: cellId } };
}

/** A deterministic, direction-independent geometry identity. This is a UI
 * grouping key, never evidence that the feature is current or navigable. */
function trackGeometryKey(pts: LatLon[]): string {
    const points = pts.map((p) => `${p.lon.toFixed(7)},${p.lat.toFixed(7)}`);
    const forward = points.join(';');
    const reverse = [...points].reverse().join(';');
    const canonical = forward < reverse ? forward : reverse;
    let h1 = 0x811c9dc5;
    let h2 = 0x9e3779b9;
    for (let i = 0; i < canonical.length; i++) {
        h1 = Math.imul(h1 ^ canonical.charCodeAt(i), 16777619);
        h2 = Math.imul(h2 ^ canonical.charCodeAt(i), 2246822519);
    }
    return `${(h1 >>> 0).toString(16).padStart(8, '0')}${(h2 >>> 0).toString(16).padStart(8, '0')}`;
}

/** IHO S-57 UOC §10.1/table 10.1: RECTRC is the recommended track;
 * NAVLNE CATNAV=1 is a clearing line, 2 is a transit/bearing, and only 3
 * bears a recommended track. Keep those identities distinct and reject
 * unknown categories. A NAVLNE=3 may still extend between marks on land:
 * this parser supplies review context, NOT permission to route along it.
 * Unlike parseLeadingLines, malformed vertices are never joined across. */
export function parseChartTrackLines(features: LineFeatureLike[], layerClass?: 'RECTRC' | 'NAVLNE'): ChartTrackLine[] {
    const out: ChartTrackLine[] = [];
    for (const feature of features) {
        const p = feature.properties ?? {};
        const declared = shortText(readS57(p, 'ACRONYM'))?.toUpperCase();
        const objectClass = declared ?? layerClass;
        const osmLeading =
            !declared &&
            layerClass !== 'RECTRC' &&
            readS57(p, 'CATNAV') === undefined &&
            readS57(p, 'CATTRK') === undefined &&
            p['seamark:type'] === 'navigation_line' &&
            p['seamark:navigation_line:category'] === 'leading';
        const category = singleCode(readS57(p, objectClass === 'RECTRC' ? 'CATTRK' : 'CATNAV'));
        const kind =
            objectClass === 'RECTRC' && (category === 1 || category === 2)
                ? 'recommended-track'
                : (objectClass === 'NAVLNE' && category === 3) || osmLeading
                  ? 'leading-line'
                  : null;
        if (!kind) continue;
        const g = feature.geometry;
        if (!g || !Array.isArray(g.coordinates)) continue;
        const rings: unknown[] =
            g.type === 'LineString' ? [g.coordinates] : g.type === 'MultiLineString' ? g.coordinates : [];
        for (const ring of rings) {
            if (
                !Array.isArray(ring) ||
                ring.length < 2 ||
                ring.length > 4096 ||
                !ring.every(
                    (c) =>
                        Array.isArray(c) &&
                        c.length >= 2 &&
                        Number.isFinite(c[0]) &&
                        Number.isFinite(c[1]) &&
                        Math.abs(c[0]) <= 180 &&
                        Math.abs(c[1]) <= 80,
                )
            )
                continue;
            const pts = ring.map((c: number[]) => ({ lon: c[0], lat: c[1] }));
            if (pts.some((q, i) => i > 0 && Math.abs(q.lon - pts[i - 1].lon) > 180)) continue;
            const sourceCell = shortText(p._cellId) ?? shortText(p.cellId) ?? shortText(p.sourceCell);
            const source = shortText(p._source) ?? shortText(p.source) ?? (osmLeading ? 'osm' : 'enc');
            const featureId =
                typeof p.rcid === 'number' && Number.isSafeInteger(p.rcid) && p.rcid >= 0
                    ? String(p.rcid)
                    : (shortText(p.rcid) ?? shortText(p['@id']));
            const name = shortText(readS57(p, 'OBJNAM')) ?? shortText(p.name);
            const identity = [sourceCell, featureId].filter(Boolean).join(' / ');
            const label =
                name ??
                `${kind === 'recommended-track' ? 'Charted recommended track' : 'Charted leading line'}${identity ? ` · ${identity}` : ''}`;
            const orientation = readS57(p, 'ORIENT');
            const typedClass = osmLeading ? 'OSM_NAVLINE' : (objectClass as 'RECTRC' | 'NAVLNE');
            out.push({
                pts,
                chartTrack: {
                    id: `${typedClass}:${sourceCell ?? source}:${featureId ?? ''}:${trackGeometryKey(pts)}`,
                    label,
                    kind,
                    objectClass: typedClass,
                    category: osmLeading ? 'leading' : category!,
                    source,
                    sourceCell,
                    featureId,
                    name,
                    orientationDeg:
                        typeof orientation === 'number' && Number.isFinite(orientation) ? orientation : undefined,
                    traffic: singleCode(readS57(p, 'TRAFIC')),
                },
            });
        }
    }
    return out;
}

/**
 * The ONE gate between a navigation line and every lead path — the grid's
 * preferred corridor and depth rescue, the snappers, the egress splice, the
 * tracer's lead snap and the land audit's "vouched water".
 *
 * A chart line (the NAVLNE layer, a declared S-57 acronym, or any CATNAV)
 * leads only when parseChartTrackLines types it as a leading line, which
 * means CATNAV exactly 3 on valid geometry:
 *   • CATNAV 1, a clearing line, marks the EDGE of a danger. It must never
 *     attract a route or vouch for depth. It stays NEUTRAL rather than
 *     becoming a keep-out boundary because the extracted chart gives no
 *     reliable safe side: the NAVLNE carries only CATNAV and ORIENT (the
 *     bearing towards the marks, which says nothing about which side is
 *     clear), and the S-57 associations to the danger it clears are not
 *     extracted. Guessing a side would invent a boundary.
 *   • CATNAV 2, a transit or bearing line, is not a track.
 *   • Missing, list-valued or unknown categories are not leads either.
 * RECTRC is not a navigation line and is not filtered here.
 *
 * OSM seamark navigation lines have no CATNAV. The Pi and the cloud overlay
 * already drop category=clearing; a clearing line that reaches here anyway is
 * dropped too. Other OSM categories keep their existing behaviour, EXCEPT
 * where the chart has drawn the same line: see withoutChartNonLeadTwins.
 */
export function isNavLineLead(feature: LineFeatureLike, layerClass?: 'NAVLNE'): boolean {
    const p = feature.properties ?? {};
    if (isChartNavLine(feature, layerClass)) {
        return parseChartTrackLines([feature], 'NAVLNE').some(
            (line) => line.chartTrack.objectClass === 'NAVLNE' && line.chartTrack.kind === 'leading-line',
        );
    }
    const osmCategory = p['seamark:navigation_line:category'];
    return !(
        typeof osmCategory === 'string' &&
        osmCategory
            .split(';')
            .map((c) => c.trim().toLowerCase())
            .includes('clearing')
    );
}

/**
 * True when a navigation line comes from an S-57 chart rather than OSM: the
 * NAVLNE layer, a declared acronym, a CATNAV, or S-57 record structure (a
 * classCode or OBJL, or an rcid). The structural test means a chart NAVLNE
 * whose extractor left out the acronym and CATNAV is still judged as a chart
 * line — and an uncategorised chart line never leads — whoever assembled the
 * layers. OSM lines carry `_osmId` and `seamark:*`, never these. Leaning to
 * "chart" is the safe side: a chart line leads only as CATNAV 3.
 */
export function isChartNavLine(feature: LineFeatureLike, layerClass?: 'NAVLNE'): boolean {
    if (layerClass === 'NAVLNE') return true;
    const p = feature.properties ?? {};
    return (
        shortText(readS57(p, 'ACRONYM')) !== undefined ||
        readS57(p, 'CATNAV') !== undefined ||
        readS57(p, 'classCode') !== undefined ||
        readS57(p, 'OBJL') !== undefined ||
        p.rcid !== undefined
    );
}

/** The navigation lines that may act as leads (see isNavLineLead). In a mixed
 * list (no layerClass), the stretch of an OSM line that is the chart's own
 * clearing or transit line drawn again is cut out as well
 * (withoutChartNonLeadTwins). Returns the input array itself when nothing is
 * dropped or cut, so callers can keep identity. */
export function navLineLeads<T extends LineFeatureLike>(features: readonly T[], layerClass?: 'NAVLNE'): T[] {
    const kept = features.filter((feature) => isNavLineLead(feature, layerClass));
    const out =
        layerClass === 'NAVLNE'
            ? kept
            : withoutChartNonLeadTwins(
                  kept,
                  features.filter((feature) => isChartNavLine(feature)),
              );
    // By identity, not length: a cut line keeps its place but is a new object.
    return out.length === features.length && out.every((feature, i) => feature === features[i])
        ? (features as T[])
        : out;
}

/** An OSM line within this distance of a chart NAVLNE, and parallel to it
 * within TWIN_DEG, is read as the same charted line. */
const TWIN_M = 30;
const TWIN_DEG = 10;
/** Sampling step along the OSM line; coarsened so no line takes more than
 * TWIN_MAX_SAMPLES samples. */
const TWIN_STEP_M = 10;
const TWIN_MAX_SAMPLES = 5_000;
/** How much of an OSM line (or half of it, if shorter) must be claimed by a
 * chart non-lead before the claimed stretch is cut out, and the shortest
 * piece left over that still leads. One 50 m engine cell. */
const TWIN_MIN_M = 50;
/** On a (near) tie the non-lead claims the sample: the safe side. */
const TWIN_TIE_M = 0.5;

interface ChartTwinCandidate {
    rings: LatLon[][];
    lead: boolean;
    /** Bbox grown by TWIN_M: [minLon, minLat, maxLon, maxLat]. */
    box: [number, number, number, number];
}

function chartTwinCandidates(
    chartNavLines: readonly LineFeatureLike[],
    chartLeadTracks: readonly LineFeatureLike[],
): ChartTwinCandidate[] {
    const out: ChartTwinCandidate[] = [];
    for (const [feature, isLeadTrack] of [
        ...chartNavLines.map((f) => [f, false] as const),
        ...chartLeadTracks.map((f) => [f, true] as const),
    ]) {
        const rings = parseLeadingLines([feature]).map((line) => line.pts);
        if (rings.length === 0) continue;
        let minLon = Infinity,
            minLat = Infinity,
            maxLon = -Infinity,
            maxLat = -Infinity;
        for (const ring of rings)
            for (const p of ring) {
                minLon = Math.min(minLon, p.lon);
                minLat = Math.min(minLat, p.lat);
                maxLon = Math.max(maxLon, p.lon);
                maxLat = Math.max(maxLat, p.lat);
            }
        const padLat = TWIN_M / 110_540;
        const cosLat = Math.cos((Math.max(Math.abs(minLat), Math.abs(maxLat)) * Math.PI) / 180);
        const padLon = TWIN_M / (111_320 * Math.max(0.01, cosLat));
        out.push({
            rings,
            lead: isLeadTrack || isNavLineLead(feature, 'NAVLNE'),
            box: [minLon - padLon, minLat - padLat, maxLon + padLon, maxLat + padLat],
        });
    }
    return out;
}

/** One sampled step along an OSM line: its span and whether a chart non-lead
 * claims it. `vertexEnd` marks a step that ends on one of the line's own
 * vertices, so a cut line keeps its shape without the sample points. */
interface ClaimStep {
    from: LatLon;
    to: LatLon;
    lengthM: number;
    claimed: boolean;
    vertexEnd: boolean;
}

/** Metres of `rings` that lie nearer — within TWIN_M and TWIN_DEG — to a
 * chart NAVLNE that is not a lead than to any chart lead, the length, and the
 * sampled steps (per ring) that say where. */
function chartNonLeadClaim(
    rings: LatLon[][],
    chart: readonly ChartTwinCandidate[],
): { claimedM: number; lengthM: number; steps: ClaimStep[][] } {
    let lengthM = 0;
    for (const ring of rings) for (let i = 1; i < ring.length; i++) lengthM += distM(ring[i - 1], ring[i]);
    const stepM = Math.max(TWIN_STEP_M, lengthM / TWIN_MAX_SAMPLES);
    let claimedM = 0;
    const steps: ClaimStep[][] = [];
    for (const ring of rings) {
        const ringSteps: ClaimStep[] = [];
        steps.push(ringSteps);
        for (let i = 1; i < ring.length; i++) {
            const a = ring[i - 1],
                b = ring[i];
            const segM = distM(a, b);
            if (!(segM >= 1)) {
                ringSteps.push({ from: a, to: b, lengthM: 0, claimed: false, vertexEnd: true });
                continue;
            }
            const bearing = bearingDeg(a, b);
            const k = Math.max(1, Math.ceil(segM / stepM));
            const along = (t: number) => ({ lat: a.lat + (b.lat - a.lat) * t, lon: a.lon + (b.lon - a.lon) * t });
            for (let s = 0; s < k; s++) {
                const t = (s + 0.5) / k;
                const p = along(t);
                let nearestLead = Infinity,
                    nearestOther = Infinity;
                for (const c of chart) {
                    if (p.lon < c.box[0] || p.lat < c.box[1] || p.lon > c.box[2] || p.lat > c.box[3]) continue;
                    for (const cRing of c.rings)
                        for (let j = 1; j < cRing.length; j++) {
                            if (distM(cRing[j - 1], cRing[j]) < 1) continue;
                            const d = projectToSegment(p, cRing[j - 1], cRing[j]).dist;
                            if (d > TWIN_M || lineAngleDiffDeg(bearing, bearingDeg(cRing[j - 1], cRing[j])) > TWIN_DEG)
                                continue;
                            if (c.lead) nearestLead = Math.min(nearestLead, d);
                            else nearestOther = Math.min(nearestOther, d);
                        }
                }
                const claimed = nearestOther <= TWIN_M && nearestOther <= nearestLead + TWIN_TIE_M;
                if (claimed) claimedM += segM / k;
                ringSteps.push({
                    from: s === 0 ? a : along(s / k),
                    to: s === k - 1 ? b : along((s + 1) / k),
                    lengthM: segM / k,
                    claimed,
                    vertexEnd: s === k - 1,
                });
            }
        }
    }
    return { claimedM, lengthM, steps };
}

/** The unclaimed runs of a sampled line, each as a polyline and its length. */
function unclaimedPieces(steps: readonly ClaimStep[][]): { pts: LatLon[]; lengthM: number }[] {
    const out: { pts: LatLon[]; lengthM: number }[] = [];
    for (const ring of steps) {
        let piece: { pts: LatLon[]; lengthM: number } | null = null;
        for (let i = 0; i < ring.length; i++) {
            const step = ring[i];
            if (step.claimed) {
                if (piece) out.push(piece);
                piece = null;
                continue;
            }
            if (!piece) piece = { pts: [step.from], lengthM: 0 };
            piece.lengthM += step.lengthM;
            const next = ring[i + 1];
            if (step.vertexEnd || !next || next.claimed) piece.pts.push(step.to);
        }
        if (piece) out.push(piece);
    }
    return out;
}

/**
 * Let the chart win where it has drawn the same line. OSM tags some chart
 * transits (CATNAV 2) as `category=transit` and keeps them as leads, so the
 * bearing lines dropped from the chart came straight back through the overlay
 * (Hamilton Reach: OSM 1050662196/1050662408 lie 1–12 m along NAVLNE 2383,
 * 1050662194/1050662407 along 3454). Where at least TWIN_MIN_M of an OSM line
 * (or half of it, if shorter) runs within TWIN_M of, and parallel within
 * TWIN_DEG to, a chart NAVLNE that is not a leading line — nearer to that
 * line than to any chart lead — that stretch is cut out of it. The chart's
 * own category then decides there. What is left keeps leading where it is at
 * least TWIN_MIN_M long; a line with nothing left goes.
 *
 * It used to drop the WHOLE line once 50 m of it was claimed, so a 60 m
 * clearing stub beside a 3 km OSM lead cost the lead all 3 km (review
 * 2026-09-29). An OSM line that is a chart LEADING line drawn again is kept
 * (unchanged behaviour); the chart lead is there either way.
 *
 * `chartNavLines` is every chart NAVLNE in play, BEFORE the lead gate, so the
 * dropped clearing and transit lines still count here. `chartLeadTracks` are
 * chart tracks that lead without being NAVLNE (RECTRC): they weigh against a
 * clearing or transit line like a chart NAVLNE lead, so an OSM redraw of a
 * RECTRC-only lead is not cut for a clearing line 25 m away. Chart lines
 * inside `lines` are left to isNavLineLead. A cut line is a new feature with
 * the same properties and MultiLineString geometry; the input is never
 * edited. Returns the input array itself when nothing is dropped or cut.
 */
export function withoutChartNonLeadTwins<T extends LineFeatureLike>(
    lines: readonly T[],
    chartNavLines: readonly LineFeatureLike[],
    chartLeadTracks: readonly LineFeatureLike[] = [],
): T[] {
    if (lines.length === 0 || !chartNavLines.some((f) => !isNavLineLead(f, 'NAVLNE'))) return lines as T[];
    const chart = chartTwinCandidates(chartNavLines, chartLeadTracks);
    if (!chart.some((c) => !c.lead)) return lines as T[];
    let changed = false;
    const out: T[] = [];
    for (const line of lines) {
        if (isChartNavLine(line)) {
            out.push(line);
            continue;
        }
        const rings = parseLeadingLines([line]).map((l) => l.pts);
        if (rings.length === 0) {
            out.push(line);
            continue;
        }
        const { claimedM, lengthM, steps } = chartNonLeadClaim(rings, chart);
        if (!(claimedM > 0 && claimedM >= Math.min(TWIN_MIN_M, lengthM / 2))) {
            out.push(line);
            continue;
        }
        changed = true;
        const pieces = unclaimedPieces(steps).filter((piece) => piece.lengthM >= TWIN_MIN_M);
        if (pieces.length === 0) continue;
        out.push({
            ...line,
            geometry: {
                type: 'MultiLineString',
                coordinates: pieces.map((piece) => piece.pts.map((p) => [p.lon, p.lat])),
            },
        });
    }
    return changed ? out : (lines as T[]);
}

/** The OSM overlay's navigation lines that may join NAVLINE: never a clearing
 * line, and never the stretch of one that is a chart clearing or transit line
 * drawn again. Pass every chart NAVLNE merged for the same area, before the
 * lead gate, and the merged RECTRC as `chartLeadTracks`. Both device merges
 * (the engine's and the tracer's) use this. */
export function osmNavLineLeads<T extends LineFeatureLike>(
    osmLines: readonly T[],
    chartNavLines: readonly LineFeatureLike[],
    chartLeadTracks: readonly LineFeatureLike[] = [],
): T[] {
    return withoutChartNonLeadTwins(navLineLeads(osmLines), chartNavLines, chartLeadTracks);
}

export interface ChartTrackOffset {
    track: ChartTrackLine['chartTrack'];
    offsetM: number;
    at: LatLon;
}

/** Identify a genuinely parallel, finite overlap, not a nearby bearing or
 * a crossing/join/departure manoeuvre. No route points are changed. The
 * closest sustained overlap wins independently of chart/feature order;
 * being on one track does not produce an offset warning for a parallel one.
 * Thresholds are review relevance only, never channel-width/clearance proof. */
export function chartTrackOffsetForLeg(
    a: LatLon,
    b: LatLon,
    tracks: readonly ChartTrackLine[],
    onIncomplete?: () => void,
): ChartTrackOffset | null {
    const legLength = distM(a, b);
    if (!Number.isFinite(legLength) || legLength < 1) return null;
    const legBearing = bearingDeg(a, b);
    const point = (t: number) => ({ lat: a.lat + (b.lat - a.lat) * t, lon: a.lon + (b.lon - a.lon) * t });
    const EPS_M = 1e-5;
    // Synchronous UI-thread validator: complex charts must become an explicit
    // incomplete advisory, not unbounded intersection/envelope work.
    let work = 0;
    const exceeded = (amount = 1) => (work += amount) > 200_000;
    const incomplete = () => {
        onIncomplete?.();
        return null;
    };
    const candidates: Array<ChartTrackOffset & { nearestM: number; overlapM: number; manoeuvre: boolean }> = [];
    for (const track of tracks) {
        // Within a segment's finite projection, signed distance is linear in
        // route parameter t. Partition at every nearest-segment switch, so a
        // U/bending track is measured against its nearest branch, not the
        // most distant parallel branch. No sampling-dependent midpoint test.
        const segments: Array<{
            c: LatLon;
            d: LatLon;
            lo: number;
            hi: number;
            o: number;
            slope: number;
            parallel: boolean;
        }> = [];
        let crosses = false;
        for (let i = 1; i < track.pts.length; i++) {
            if (exceeded()) return incomplete();
            const c = track.pts[i - 1],
                d = track.pts[i];
            const segmentLength = distM(c, d);
            if (segmentLength < 1) continue;
            const mLon = 111_320 * Math.cos((c.lat * Math.PI) / 180);
            const dx = (d.lon - c.lon) * mLon,
                dy = (d.lat - c.lat) * 110_540;
            const len2 = dx * dx + dy * dy;
            const ax = (a.lon - c.lon) * mLon,
                ay = (a.lat - c.lat) * 110_540;
            const lx = (b.lon - a.lon) * mLon,
                ly = (b.lat - a.lat) * 110_540;
            const denominator = lx * dy - ly * dx;
            if (Math.abs(denominator) > 1e-6) {
                const routeT = (-ax * dy + ay * dx) / denominator;
                const lineT = (-ax * ly + ay * lx) / denominator;
                if (routeT >= 0 && routeT <= 1 && lineT >= 0 && lineT <= 1) crosses = true;
            }
            const projection = (q: LatLon) => ((q.lon - c.lon) * mLon * dx + (q.lat - c.lat) * 110_540 * dy) / len2;
            const sa = projection(a),
                sb = projection(b),
                ds = sb - sa;
            if (Math.abs(ds) < 1e-10) continue;
            let lo = Math.max(0, Math.min(-sa / ds, (1 - sa) / ds));
            let hi = Math.min(1, Math.max(-sa / ds, (1 - sa) / ds));
            if (hi <= lo) continue; // Outside the finite charted extent.
            const o = (dx * ay - dy * ax) / Math.sqrt(len2);
            const slope = (dx * ly - dy * lx) / Math.sqrt(len2);
            if (Math.abs(slope) > 1e-8) {
                const r0 = (-150 - o) / slope,
                    r1 = (150 - o) / slope;
                lo = Math.max(lo, Math.min(r0, r1));
                hi = Math.min(hi, Math.max(r0, r1));
            } else if (Math.abs(o) > 150 + EPS_M) continue;
            if (hi <= lo) continue;
            segments.push({ c, d, lo, hi, o, slope, parallel: lineAngleDiffDeg(legBearing, bearingDeg(c, d)) <= 15 });
            if (segments.length > 256) return incomplete();
        }
        const breaks = segments.flatMap((s) => [s.lo, s.hi]);
        for (const s of segments)
            for (const target of [-40, 0, 40]) {
                const t = (target - s.o) / s.slope;
                if (Number.isFinite(t) && t > s.lo && t < s.hi) breaks.push(t);
            }
        for (let i = 0; i < segments.length; i++)
            for (let j = i + 1; j < segments.length; j++) {
                if (exceeded() || breaks.length > 4096) return incomplete();
                const x = segments[i],
                    y = segments[j];
                const lo = Math.max(x.lo, y.lo),
                    hi = Math.min(x.hi, y.hi);
                if (lo >= hi) continue;
                for (const sign of [-1, 1]) {
                    const t = -(x.o + sign * y.o) / (x.slope + sign * y.slope);
                    if (Number.isFinite(t) && t > lo && t < hi) breaks.push(t);
                }
            }
        breaks.sort((x, y) => x - y);
        let overlapM = 0,
            distanceIntegral = 0,
            maxOffsetM = 0,
            onM = 0,
            offM = 0;
        let at: LatLon | null = null;
        for (let i = 1; i < breaks.length; i++) {
            if (exceeded(segments.length)) return incomplete();
            const lo = breaks[i - 1],
                hi = breaks[i],
                mid = (lo + hi) / 2;
            if (hi - lo < 1e-10) continue;
            const nearest = segments
                .filter((s) => mid >= s.lo && mid <= s.hi)
                .sort((x, y) => Math.abs(x.o + x.slope * mid) - Math.abs(y.o + y.slope * mid))[0];
            if (!nearest?.parallel) continue;
            const d0 = Math.abs(nearest.o + nearest.slope * lo),
                d1 = Math.abs(nearest.o + nearest.slope * hi);
            const length = (hi - lo) * legLength,
                high = Math.max(d0, d1);
            overlapM += length;
            distanceIntegral += ((d0 + d1) / 2) * length;
            if (Math.abs(nearest.o + nearest.slope * mid) <= 40 + EPS_M) onM += length;
            else offM += length;
            if (!at || high > maxOffsetM + EPS_M) {
                maxOffsetM = high;
                at = projectToSegment(point(d0 >= d1 ? lo : hi), nearest.c, nearest.d).point;
            }
        }
        if (!at || overlapM + EPS_M < Math.min(100, legLength * 0.5)) continue;
        candidates.push({
            track: track.chartTrack,
            offsetM: maxOffsetM,
            at,
            nearestM: distanceIntegral / overlapM,
            overlapM,
            manoeuvre: crosses || (onM > EPS_M && offM > EPS_M),
        });
    }
    candidates.sort(
        (x, y) =>
            x.nearestM - y.nearestM ||
            y.overlapM - x.overlapM ||
            Number(x.track.kind !== 'recommended-track') - Number(y.track.kind !== 'recommended-track') ||
            x.track.id.localeCompare(y.track.id),
    );
    const best = candidates[0];
    return best && !best.manoeuvre && best.offsetM > 40 + EPS_M
        ? { track: best.track, offsetM: best.offsetM, at: best.at }
        : null;
}

export interface SnapOptions {
    /** Route vertex within this of a line counts as "on the corridor". */
    corridorM?: number;
    /** Minimum transit length to snap (avoid snapping a brush-by). */
    minRunM?: number;
    /** Max UNDIRECTED angle between the route run and the line for it to count
     *  as a genuine transit (vs a perpendicular crossing). */
    maxAngleDeg?: number;
    /** Hard land (NaN/out-of-grid) test. The spliced run is validated against
     *  it — never snap a transit across solid land. */
    isBlocked?: (p: LatLon) => boolean;
    /** Caution (shallow/soft) test. Used only to flag the on-line segment's
     *  caution HONESTLY — it stays red if the transit genuinely crosses caution
     *  water, clean where Pass 5b rescued the leading-line corridor. */
    isCaution?: (p: LatLon) => boolean;
    /** AUTHORITATIVE tracks (RECTRC — the hydrographer's recommended centreline)
     *  the route must NOT be dragged off. A candidate run whose midpoint already
     *  rides within `protectM` of one of these lines is on the official track:
     *  the leading-line (NAVLNE) snap is SKIPPED for it so RECTRC wins over the
     *  deliberately-off-centre transit. Empty/undefined ⇒ no protection (today's
     *  behaviour, e.g. canals with no recommended track). */
    protect?: LeadingLine[];
    /** How close a run's sampled body must be to a `protect` line to count as
     *  "on the recommended track" and veto the lead snap (metres). */
    protectM?: number;
    /** Follow the line's OWN interior vertices when snapping onto a BENDING line
     *  (curved RECTRC recommended track) instead of collapsing the run to a
     *  straight chord — which cuts the inside of every bend and pins the route to
     *  one bank. OFF by default so straight leading lines + the synthetic channel
     *  chains stay byte-identical; set ONLY at the RECTRC call sites. A straight
     *  line is a no-op either way. */
    followInteriorVertices?: boolean;
}

export interface SnapResult {
    polyline: LatLon[];
    cautionMask: boolean[];
    /** Number of leading lines the route was snapped onto. */
    snapped: number;
}

/**
 * Snap a route onto the charted leading lines it transits. For each line, find
 * the contiguous run of route vertices that hugs it (within `corridorM`), is
 * long enough (`minRunM`) and roughly parallel (`maxAngleDeg`), then replace
 * that run with the straight on-line segment between the run's projected
 * endpoints — the literal transit. The route's first/last vertices (origin and
 * destination) are NEVER moved. The spliced run is validated against
 * `isBlocked`; any solid-land crossing aborts that snap and leaves the route.
 *
 * The cautionMask is carried through: the on-line segment is flagged caution
 * only if it genuinely crosses caution water — so a snapped transit goes from
 * red "near the channel" to clean "on the channel", honestly.
 */
export function snapToLeadingLines(
    polyline: LatLon[],
    cautionMask: boolean[],
    lines: LeadingLine[],
    opts: SnapOptions = {},
): SnapResult {
    const corridorM = opts.corridorM ?? 120;
    const minRunM = opts.minRunM ?? 150;
    const maxAngleDeg = opts.maxAngleDeg ?? 35;
    const { isBlocked, isCaution } = opts;
    const protect = opts.protect ?? [];
    const protectM = opts.protectM ?? 70;
    const followInteriorVertices = opts.followInteriorVertices ?? false;

    /** True if EVERY sampled point of poly[from..to] already rides within
     *  protectM of a protect (RECTRC) line — i.e. the run is on the official
     *  recommended track and must not be dragged off onto a leading line. A run
     *  that only partly overlaps the track is NOT protected (the off-track part
     *  may legitimately want the lead). */
    const onProtectedTrack = (from: number, to: number): boolean => {
        if (protect.length === 0) return false;
        for (let k = from; k <= to; k++) {
            const onAny = protect.some((pl) => projectToLine(poly[k], pl.pts).dist < protectM);
            if (!onAny) return false;
        }
        return true;
    };

    let poly = polyline.slice();
    let caution = cautionMask.slice();
    let snapped = 0;

    for (const line of lines) {
        // Need ≥4 vertices so clamping to the interior still leaves a real run.
        if (poly.length < 4 || line.pts.length < 2) continue;

        // Which route vertices hug this line?
        const near = poly.map((v) => projectToLine(v, line.pts).dist < corridorM);

        // Longest contiguous run of `near`.
        let bestStart = -1;
        let bestEnd = -1;
        let i = 0;
        while (i < near.length) {
            if (!near[i]) {
                i++;
                continue;
            }
            let j = i;
            while (j + 1 < near.length && near[j + 1]) j++;
            if (j - i > bestEnd - bestStart) {
                bestStart = i;
                bestEnd = j;
            }
            i = j + 1;
        }
        if (bestStart < 0) continue;

        // Keep origin + destination fixed: clamp the run to the interior.
        const runStart = Math.max(1, bestStart);
        const runEnd = Math.min(poly.length - 2, bestEnd);
        if (runStart >= runEnd) continue;

        // Long enough to be a genuine transit, not a momentary brush-by?
        if (runLengthM(poly, runStart, runEnd) < minRunM) continue;

        // Roughly parallel to the line (else it's a perpendicular crossing)?
        const runBearing = bearingDeg(poly[runStart], poly[runEnd]);
        const lineBearing = bearingDeg(line.pts[0], line.pts[line.pts.length - 1]);
        if (lineAngleDiffDeg(runBearing, lineBearing) > maxAngleDeg) continue;

        // RECTRC wins: if this run already rides the recommended track, never
        // pull it off onto the (deliberately off-centre) leading line.
        if (onProtectedTrack(runStart, runEnd)) continue;

        // Project the run endpoints onto the line.
        const pa = projectToLineIndexed(poly[runStart], line.pts);
        const pb = projectToLineIndexed(poly[runEnd], line.pts);
        const projA = pa.point;
        const projB = pb.point;

        // What we EMIT: the line's own interior vertices for a BENDING opted-in line
        // (follow the curved RECTRC, no inside-of-bend wall-hug), else the straight
        // chord. A straight line yields [projA, projB] either way → byte-identical.
        const onLine = followInteriorVertices ? onLineSubPolyline(line.pts, pa, pb) : [projA, projB];
        const useInterior = onLine.length > 2;

        // Never snap across solid land — validate the ACTUAL emitted geometry
        // (entry-bridge + the emitted run + exit-bridge), not a chord we don't emit.
        const emit = useInterior ? onLine : [projA, projB];
        const spliced = [poly[runStart - 1], ...emit, poly[runEnd + 1]];
        if (isBlocked && anyAlong(spliced, 25, isBlocked)) continue;

        // Honest caution: the on-line run stays red only if it actually crosses
        // caution water (it won't, where Pass 5b rescued the corridor).
        const onLineCaution = isCaution ? anyAlong(emit, 25, isCaution) : false;

        if (useInterior) {
            // Follow the curve: replace [runStart..runEnd] with the on-line sub-polyline.
            // (lengths reconcile: K emitted vertices + caution.slice(runEnd+1).)
            poly = [...poly.slice(0, runStart), ...onLine, ...poly.slice(runEnd + 1)];
            caution = [...caution.slice(0, runStart), ...onLine.map(() => onLineCaution), ...caution.slice(runEnd + 1)];
        } else {
            // Original chord splice — byte-identical to the pre-change behaviour.
            poly = [...poly.slice(0, runStart), projA, projB, ...poly.slice(runEnd + 1)];
            caution = [...caution.slice(0, runStart), onLineCaution, ...caution.slice(runEnd)];
        }
        snapped++;
    }

    return { polyline: poly, cautionMask: caution, snapped };
}

export interface LeadingApproach {
    /** Capture point on the outermost transit's seaward extension — the
     *  route's divert target ("stand off, then get on the leads"). */
    anchor: LatLon;
    /** The sailed transit run: [anchor, turn(s)…, breakOff, dest]. Every
     *  vertex lies on a transit LINE in open water — never at a beacon. */
    chain: LatLon[];
    /** How many leading lines the approach uses (1 = single transit,
     *  2 = a dog-leg). */
    lineCount: number;
}

/**
 * Build the charted leading-line APPROACH to a destination as the skipper
 * actually sails it. A leading line's charted geometry is the segment between
 * its two BEACONS — which routinely stand ON shore or drying banks. You never
 * sail to a beacon: you sail the transit LINE (the marks kept in line),
 * offset seaward of them. So the approach is built from transit-line
 * geometry, not mark positions:
 *
 *   • breakOff = the destination projected onto the inner transit line —
 *     ride the lead until abeam the anchorage, then break off.
 *   • For a dog-leg, the turn = the INTERSECTION of the two transit lines;
 *     you ride the outer transit to the turn, then the inner transit in.
 *   • anchor = a capture point `captureM` back along the outer transit's
 *     seaward extension — where the route joins the lead.
 *
 * A line "serves" the destination when its nearer end is within `maxDestM`.
 * Returns null when no leading line serves the destination (normal routing).
 */
export function buildLeadingApproach(
    dest: LatLon,
    lines: LeadingLine[],
    opts: { maxDestM?: number; linkM?: number; captureM?: number } = {},
): LeadingApproach | null {
    const maxDestM = opts.maxDestM ?? 1500;
    const linkM = opts.linkM ?? 1800;
    const captureM = opts.captureM ?? 800;
    if (lines.length === 0) return null;

    // Local planar metres around the destination (the whole approach spans a
    // few km at most — equirectangular is plenty).
    const mPerLat = 110_540;
    const mPerLon = 111_320 * Math.cos((dest.lat * Math.PI) / 180);
    const toM = (p: LatLon): { x: number; y: number } => ({
        x: (p.lon - dest.lon) * mPerLon,
        y: (p.lat - dest.lat) * mPerLat,
    });
    const fromM = (m: { x: number; y: number }): LatLon => ({
        lat: dest.lat + m.y / mPerLat,
        lon: dest.lon + m.x / mPerLon,
    });

    interface Oriented {
        seaward: LatLon;
        landward: LatLon;
    }
    // Orient each line: landward = the end nearer the destination. (Used for
    // serving/chaining and the OUTER sail direction; the inner sail direction
    // is derived from the turn geometry, which is robust even when the
    // destination lies between the inner marks.)
    const oriented: Oriented[] = lines
        .filter((l) => l.pts.length >= 2 && distM(l.pts[0], l.pts[l.pts.length - 1]) > 10)
        .map((l) => {
            const a = l.pts[0];
            const b = l.pts[l.pts.length - 1];
            return distM(a, dest) <= distM(b, dest) ? { landward: a, seaward: b } : { landward: b, seaward: a };
        });

    // Serving lines: landward end within maxDestM of the destination.
    const serving = oriented.filter((o) => distM(o.landward, dest) <= maxDestM);
    if (serving.length === 0) return null;

    // Innermost = the serving line whose landward end is nearest the destination.
    serving.sort((p, q) => distM(p.landward, dest) - distM(q.landward, dest));
    const inner = serving[0];

    // Find the OUTER lead of a dog-leg: the line whose landward end links to
    // the inner's seaward end within linkM (the charted hand-off).
    let outer: Oriented | null = null;
    let outerD = linkM;
    for (const o of oriented) {
        if (o === inner) continue;
        const d = distM(o.landward, inner.seaward);
        if (d < outerD) {
            outerD = d;
            outer = o;
        }
    }

    // Inner transit line (point + unit direction, metres).
    const iA = toM(inner.seaward);
    const iB = toM(inner.landward);
    const iLen = Math.hypot(iB.x - iA.x, iB.y - iA.y);
    const iDir = { x: (iB.x - iA.x) / iLen, y: (iB.y - iA.y) / iLen };
    // breakOff = dest (origin) projected onto the inner transit line.
    const tBreak = -(iA.x * iDir.x + iA.y * iDir.y);
    const breakM = { x: iA.x + iDir.x * tBreak, y: iA.y + iDir.y * tBreak };
    // Sanity: the lead must actually point at the anchorage.
    if (Math.hypot(breakM.x, breakM.y) > maxDestM) return null;
    const breakOff = fromM(breakM);

    if (outer) {
        // Dog-leg: turn at the intersection of the two transit lines.
        const oA = toM(outer.seaward);
        const oB = toM(outer.landward);
        const oLen = Math.hypot(oB.x - oA.x, oB.y - oA.y);
        const oDir = { x: (oB.x - oA.x) / oLen, y: (oB.y - oA.y) / oLen };
        const denom = oDir.x * iDir.y - oDir.y * iDir.x;
        if (Math.abs(denom) > 1e-6) {
            // Solve oA + s·oDir = iA + t·iDir.
            const dx = iA.x - oA.x;
            const dy = iA.y - oA.y;
            const s = (dx * iDir.y - dy * iDir.x) / denom;
            const turnM = { x: oA.x + oDir.x * s, y: oA.y + oDir.y * s };
            const turnToBreakM = Math.hypot(breakM.x - turnM.x, breakM.y - turnM.y);
            // Course change at the turn: outer sail dir (toward its marks)
            // onto the run-in dir (turn → breakOff).
            const inDir = { x: (breakM.x - turnM.x) / turnToBreakM, y: (breakM.y - turnM.y) / turnToBreakM };
            const cosTurn = oDir.x * inDir.x + oDir.y * inDir.y;
            // A genuine dog-leg: a real run between turn and break-off, and a
            // moderate course change (< ~120°). Degenerate → single-lead.
            if (turnToBreakM > 50 && turnToBreakM < 5000 && cosTurn > -0.5) {
                const anchorM = { x: turnM.x - oDir.x * captureM, y: turnM.y - oDir.y * captureM };
                const anchor = fromM(anchorM);
                return { anchor, chain: [anchor, fromM(turnM), breakOff, dest], lineCount: 2 };
            }
        }
    }

    // Single transit: capture point captureM seaward of the break-off along
    // the inner transit's seaward extension.
    const anchorM = { x: breakM.x - iDir.x * captureM, y: breakM.y - iDir.y * captureM };
    const anchor = fromM(anchorM);
    return { anchor, chain: [anchor, breakOff, dest], lineCount: 1 };
}
