// GENERATED by pi-cache/scripts/sync-router-engine.mjs from utils/createLogger.ts.
// Do not edit here: change the app copy, then re-run the script (see pi-cache/src/services/inshoreRouter.ts).
/**
 * The Pi's stand-in for the app's utils/createLogger: the same interface,
 * without Sentry or import.meta.env. As in the app's production build, debug
 * and info are silent when NODE_ENV=production (the systemd unit sets it);
 * warn and error go to the journal.
 */
export interface Logger {
    debug: (...args: unknown[]) => void;
    info: (...args: unknown[]) => void;
    warn: (...args: unknown[]) => void;
    error: (...args: unknown[]) => void;
}

const IS_PROD = process.env.NODE_ENV === 'production';
const noop = (..._args: unknown[]): void => {};

export function createLogger(tag: string): Logger {
    const prefix = `[${tag}]`;
    return {
        debug: IS_PROD ? noop : (...args: unknown[]) => console.debug(prefix, ...args),
        info: IS_PROD ? noop : (...args: unknown[]) => console.info(prefix, ...args),
        warn: (...args: unknown[]) => console.warn(prefix, ...args),
        error: (...args: unknown[]) => console.error(prefix, ...args),
    };
}

export function getErrorMessage(err: unknown): string {
    if (err instanceof Error) return err.message;
    if (typeof err === 'string') return err;
    return String(err);
}
