// GENERATED by pi-cache/scripts/sync-router-engine.mjs from services/engine/chartWaterEvidence.ts.
// Do not edit here: change the app copy, then re-run the script (see pi-cache/src/services/inshoreRouter.ts).
/**
 * What counts as water where chart land paint says land — decided ONCE, for
 * the nav grid (navGrid Pass 1/2) and the final-route land audit
 * (safetyAudit.auditUnvouchedHardLand), so the independent veto can never
 * vouch for land the grid kept as land (Phase 2a review, 2026-09-30).
 *
 *   • OSM-vouched engineered water (marina, canal, dock, river, the injected
 *     OSM / Mapbox `natural=water` polygons): trusted over chunky LNDARE —
 *     unchanged doctrine.
 *   • An S-57 depth band (DEPARE, or DRGARE — a dredged area's DRVAL1 is its
 *     charted depth): only under owner decision 1 — the finest band on the
 *     spot is charted at a strictly FINER scale than the finest land paint
 *     there, and never dries (services/enc/scaleShadow.ts). A drying,
 *     undepthed, equal-scale, coarser or unranked band leaves the land paint
 *     standing.
 *   • Owner decision 12 (2026-10-02) first: land paint from overview and
 *     general cells only (usage band 1–2) is no land at all where a detailed
 *     chart (band 3+) charts a depth that never dries (landPaintStanding;
 *     scaleShadow overviewLandYields) — the spot is the detailed chart's
 *     water, never decision-1 'charts disagree'. Over a detailed DRYING band
 *     the land paint stands, as decision 1 has it.
 *   • A FAIRWY is a route area, not a depth claim: never water evidence.
 */
import {
    bandNeverDries,
    DETAILED_CHART_MIN_BAND,
    finerBandBeatsLand,
    finestSurveyOwners,
    isDetailedChartRank,
    landRankKey,
    overviewLandYields,
} from '../enc/scaleShadow.js';
import { isS57ChartProps, readS57 } from '../enc/types.js';

/**
 * Authoritative engineered water from OSM (or injected as OSM water) — the
 * DEPARE features the grid protects against LNDARE bleed. S-57 chart bands
 * (an `acronym`, or the ogr2ogr path's OBJL: isS57ChartProps) are NOT this:
 * they answer to decision 1.
 *
 * `landuse=basin` and `water=basin` are deliberately absent (2026-05-14):
 * suburban OSM tags inland stormwater retention ponds with them; on the
 * Redcliffe Peninsula there are dozens, each one a phantom 3–4 m corridor
 * across land. Real marina basins are `leisure=marina`, real canals
 * `waterway=canal`.
 */
export function isAuthoritativeOsmWater(props: Record<string, unknown> | null | undefined): boolean {
    if (!props || isS57ChartProps(props)) return false;
    const leisure = props['leisure'];
    const waterway = props['waterway'];
    const water = props['water'];
    const natural = props['natural'];
    const harbour = props['harbour'];
    return (
        leisure === 'marina' ||
        waterway === 'dock' ||
        waterway === 'canal' ||
        waterway === 'fairway' ||
        waterway === 'river' ||
        waterway === 'riverbank' ||
        // `water=*` subtags for marina contexts (Newport canals use these
        // for the side arms branching off the main basin)
        water === 'canal' ||
        water === 'harbour' ||
        water === 'marina' ||
        water === 'dock' ||
        water === 'river' ||
        water === 'lake' ||
        // OsmRouteOverlayService injects natural=water polygons into DEPARE
        // for rivers / harbours / basins (and the Mapbox canal fill carries
        // it too): OSM-derived navigable water, authoritative over LNDARE
        // bleed.
        natural === 'water' ||
        harbour === 'yes'
    );
}

/** A chart depth band's claim on a spot: its fineness rank (null =
 * unranked) and whether its charted DRVAL1 never dries. */
export interface BandClaim {
    rank: number | null;
    neverDries: boolean;
}

/** Read an S-57 DEPARE / DRGARE feature's band claim (null: not an S-57
 * band — no acronym or OBJL). */
export function bandClaimOf(props: Record<string, unknown> | null | undefined): BandClaim | null {
    if (!props || !isS57ChartProps(props)) return null;
    const rank = typeof props._scaleRank === 'number' ? props._scaleRank : null;
    const raw = readS57(props, 'DRVAL1');
    return { rank, neverDries: bandNeverDries(typeof raw === 'number' ? raw : null) };
}

/**
 * The land paint that STANDS at one spot (owner decision 12, Shane
 * 2026-10-02: "Trust the detailed chart"): none where the finest land paint
 * there is an overview or general chart's (usage band 1–2) and the depth bands
 * that own the spot (the finest survey and every band tied with it) are a
 * detailed chart's (band 3+) that all never dry — scaleShadow
 * overviewLandYields, the grid's own rule (navGrid Pass 2). Otherwise all of
 * it, unchanged: a detailed chart's land, land of unknown scale, and land over
 * a drying, undepthed, unranked or small-scale band keep decision 1.
 */
export function landPaintStanding(
    bands: readonly BandClaim[],
    landRanks: readonly (number | null)[],
): readonly (number | null)[] {
    if (landRanks.length === 0) return landRanks;
    let land = -Infinity;
    for (const r of landRanks) {
        if (r === null) return landRanks; // unknown scale: it stands
        const key = landRankKey(r);
        if (key > land) land = key;
    }
    const { owners, rank } = finestSurveyOwners(bands.map((b) => b.rank));
    const neverDry = owners.length > 0 && owners.every((i) => bands[i].neverDries);
    return overviewLandYields(rank, neverDry, land) ? [] : landRanks;
}

/** What the charts say of land at one spot, given every S-57 band and every
 * land paint covering it: 'open' — no land paint stands (none, or decision 12
 * ignores it); 'conflict' — decision-1 water, a finer never-drying band under
 * coarser land paint (water, never clear: the charts disagree); 'land'. */
export type ChartLandVerdict = 'open' | 'conflict' | 'land';

export function chartLandVerdict(bands: readonly BandClaim[], landRanks: readonly (number | null)[]): ChartLandVerdict {
    const land = landPaintStanding(bands, landRanks);
    if (land.length === 0) return 'open';
    return finestBandBeatsLand(bands, land) ? 'conflict' : 'land';
}

/**
 * Decision 1 at one spot, given every S-57 band and every land paint that
 * covers it: does the FINEST band beat the FINEST land paint? The grid's
 * per-cell rule, for a single point:
 *   • land: the finest ranked paint (by landRankKey: a paint known by its
 *     usage band alone counts as that band's finest); any unranked paint
 *     poisons it (unknown);
 *   • bands: the finest ranked band owns the spot with every band tied with
 *     it (scaleShadow surveyRanksTie) — and every owner must never dry; an
 *     unranked band counts only when no ranked band covers the spot, and then
 *     the rank is unknown and cannot beat anything.
 */
export function finestBandBeatsLand(bands: readonly BandClaim[], landRanks: readonly (number | null)[]): boolean {
    if (landRanks.length === 0) return false;
    let land: number | null = -Infinity;
    for (const r of landRanks) {
        if (r === null) {
            land = null;
            break;
        }
        const key = landRankKey(r);
        if (key > (land as number)) land = key;
    }
    if (land === null) return false;
    // The finest ranked band and every band TIED with it own the spot
    // (scaleShadow finestSurveyOwners; round-2 review, 2026-09-30).
    const { owners, rank } = finestSurveyOwners(bands.map((b) => b.rank));
    if (rank === null) return false;
    return owners.every((i) => bands[i].neverDries) && finerBandBeatsLand(rank, land);
}

// ── The satellite land check's chart evidence (2026-10-02) ──────────────────

/**
 * What the installed charts say at one point, for the satellite land check
 * (services/routing/landBackstop):
 *   • 'water' — a chart finer than NOAA ETOPO's ~1.8 km pixel charts water
 *     that never dries here (decision 1 over any land paint);
 *   • 'osm-water' — the charts do not vouch here, but the route's own
 *     navigable OSM water (a marina, canal, dock, river or harbour polygon)
 *     covers it. Neutral: the check never counts it as land, and a short
 *     stretch of it does not break a land run (review fix-up, 2026-10-02: two
 *     OSM ponds inside Hamilton Island split its land run in three, and on a
 *     small island land / pond / land would have passed as two lone samples);
 *   • 'land' — a detailed chart (or land of unknown scale, such as an OSM
 *     breakwater) owns the spot as land, or its finest survey charts drying
 *     ground or no depth;
 *   • 'uncharted' — no chart finer than ETOPO's pixel says anything here: a
 *     chart gap, or only overview cells, which generalise small islands away;
 *   • 'uncharted-land' — as 'uncharted', and a small-scale (overview or
 *     general) chart paints land here too — the Bribie class, where the words
 *     must not imply water that isn't there.
 */
export type ChartWaterVerdict = 'water' | 'osm-water' | 'land' | 'uncharted' | 'uncharted-land';
export type ChartWaterProbe = (lon: number, lat: number) => ChartWaterVerdict;

/**
 * The coarsest S-57 usage band that may vouch for water against ETOPO: 3,
 * coastal (compilation scale 1:350,000 or finer, or a band-3+ cell name).
 * Overview and general cells (bands 1–2, e.g. 1:1,500,000 and 1:3,500,000)
 * never vouch: they generalise small islands away (Armit Island, ~1 km,
 * exists only from the 1:90,000 AU421148 up), and an island they leave out
 * is exactly what ETOPO is there to catch (Claude's call, 2026-10-02).
 * The same line as owner decision 12's "detailed chart" (scaleShadow
 * DETAILED_CHART_MIN_BAND): one rule, never forked.
 */
export const BACKSTOP_MIN_VOUCH_BAND = DETAILED_CHART_MIN_BAND;

const detailed = isDetailedChartRank;

/** OSM `water=*` still-water subtags — inland ponds, not a way in or out. */
const STILL_WATER = new Set(['reservoir', 'pond', 'basin', 'lagoon', 'wastewater']);

/**
 * The OSM water the satellite land check may hear from (review fix-up,
 * 2026-10-02): the engine's authoritative OSM water (isAuthoritativeOsmWater)
 * less two kinds the grid trusts but this independent check must not —
 *   • still water (`water=reservoir / pond / basin / lagoon / wastewater`):
 *     the Airlie overlay holds 14 such inland polygons, and two of them, on
 *     Hamilton Island, broke the island's land run;
 *   • the Mapbox vector or satellite-texture water the router injects round
 *     the route's ends (`_source: 'mapbox-water'`): satellite water can read
 *     smooth sand or mud as water, and inside those crops nothing else would
 *     check it. The Newport canals need neither — their OSM canal polygons
 *     carry them (verified with Mapbox off).
 * Marina, canal, dock, river, riverbank and harbour water stay.
 */
export function isBackstopOsmWater(props: Record<string, unknown> | null | undefined): boolean {
    if (!props || !isAuthoritativeOsmWater(props)) return false;
    if (props['_source'] === 'mapbox-water') return false;
    const water = props['water'];
    return !(typeof water === 'string' && STILL_WATER.has(water));
}

/**
 * The satellite land check's verdict at one spot, from every claim on it:
 * whether the route's own navigable OSM water covers it (isBackstopOsmWater),
 * the S-57 depth bands (DEPARE / DRGARE, with their decision-1 claims) and the
 * land paint ranks (null = unranked). Decision 1 decides between land and
 * band exactly as the grid and the audit do (finestBandBeatsLand); the scale
 * rule then lets only a detailed chart vouch:
 *   • no detailed band and no detailed-or-unranked land → 'uncharted', or
 *     'uncharted-land' where small-scale land paint covers the spot;
 *   • land paint on the spot → 'water' only where the finest band beats it,
 *     that band is detailed and no band of unknown scale dries there, else
 *     'land';
 *   • no land paint → 'water' only where the finest survey owners (and any
 *     band of unknown scale) never dry, else 'land' (drying or undepthed).
 * The charts decide first; OSM water only makes a spot they do not vouch for
 * 'osm-water' (neutral), never 'water'.
 */
export function backstopVerdict(
    osmWater: boolean,
    bands: readonly BandClaim[],
    landRanks: readonly (number | null)[],
): ChartWaterVerdict {
    // Decision 12: overview land the detailed chart's depth overrides is not
    // land here either (it already could not vouch or make 'land' alone).
    const charts = chartsVerdict(bands, landPaintStanding(bands, landRanks));
    return charts !== 'water' && osmWater ? 'osm-water' : charts;
}

function chartsVerdict(bands: readonly BandClaim[], landRanks: readonly (number | null)[]): ChartWaterVerdict {
    const anyDetailedBand = bands.some((b) => detailed(b.rank));
    const anyDetailedLand = landRanks.some((r) => r === null || detailed(r));
    if (!anyDetailedBand && !anyDetailedLand) return landRanks.length > 0 ? 'uncharted-land' : 'uncharted';
    // A band of unknown scale may be a harbour survey finer than any ranked
    // one: where it dries it cancels a vouch, with or without land paint
    // (review fix-up, 2026-10-02: the land-paint branch used to skip it).
    const unrankedDries = bands.some((b) => b.rank === null && !b.neverDries);
    if (landRanks.length > 0) {
        if (!finestBandBeatsLand(bands, landRanks)) return 'land';
        return detailed(finestSurveyOwners(bands.map((b) => b.rank)).rank) && !unrankedDries ? 'water' : 'land';
    }
    const { owners, rank } = finestSurveyOwners(bands.map((b) => b.rank));
    if (!detailed(rank)) return 'uncharted';
    const dry = owners.some((i) => !bands[i].neverDries) || unrankedDries;
    return dry ? 'land' : 'water';
}
