// GENERATED by pi-cache/scripts/sync-router-engine.mjs from services/engine/geometry.ts.
// Do not edit here: change the app copy, then re-run the script (see pi-cache/src/services/inshoreRouter.ts).
/**
 * Inshore Router Engine — geometry primitives & grid-coordinate helpers.
 * Carved out of inshoreRouterEngine.ts (module split, 2026-06-24).
 * Layer 3: depends only on constants + types. bresenhamCells lives HERE
 * (not in aStar) because buildNavGrid in navGrid.ts calls it — keeping the
 * dependency arrow pointing downward.
 */
import type { Polygon, MultiPolygon, Position } from 'geojson';
import type { NavGrid } from './types.js';

export function mPerDegLon(lat: number): number {
    return 111_320 * Math.cos((lat * Math.PI) / 180);
}

/** Great-circle distance in meters using the haversine formula. */
export function haversineM(lat1: number, lon1: number, lat2: number, lon2: number): number {
    const R = 6_371_000;
    const φ1 = (lat1 * Math.PI) / 180;
    const φ2 = (lat2 * Math.PI) / 180;
    const dφ = ((lat2 - lat1) * Math.PI) / 180;
    const dλ = ((lon2 - lon1) * Math.PI) / 180;
    const a = Math.sin(dφ / 2) ** 2 + Math.cos(φ1) * Math.cos(φ2) * Math.sin(dλ / 2) ** 2;
    return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

/**
 * Ray-casting point-in-polygon for a single ring.
 * Coordinates are [lon, lat]. Returns true if (lon, lat) is inside.
 */
export function pointInRing(lon: number, lat: number, ring: Position[]): boolean {
    let inside = false;
    for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
        const xi = ring[i][0];
        const yi = ring[i][1];
        const xj = ring[j][0];
        const yj = ring[j][1];
        const intersects = yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi;
        if (intersects) inside = !inside;
    }
    return inside;
}

/**
 * Point-in-(Polygon|MultiPolygon). Outer ring contains; inner rings
 * (holes) subtract. Polygon[0] is outer, Polygon[1+] are holes.
 */
export function pointInGeometry(lon: number, lat: number, geom: Polygon | MultiPolygon): boolean {
    if (geom.type === 'Polygon') {
        if (!pointInRing(lon, lat, geom.coordinates[0])) return false;
        for (let h = 1; h < geom.coordinates.length; h++) {
            if (pointInRing(lon, lat, geom.coordinates[h])) return false; // in hole
        }
        return true;
    }
    // MultiPolygon
    for (const poly of geom.coordinates) {
        if (!pointInRing(lon, lat, poly[0])) continue;
        let inHole = false;
        for (let h = 1; h < poly.length; h++) {
            if (pointInRing(lon, lat, poly[h])) {
                inHole = true;
                break;
            }
        }
        if (!inHole) return true;
    }
    return false;
}

/**
 * Metres between the segments a→b and c→d ([lon, lat]), in a local plane of
 * kx metres per degree of longitude and ky per degree of latitude: 0 where
 * they cross or touch. Exact for that plane — what a keep-out is measured
 * with (round-2 review fix-up, 2026-10-03: a route's clearance from a shallow
 * band's edge, and a hazard area's buffer).
 */
export function segmentDistanceM(
    a: readonly number[],
    b: readonly number[],
    c: readonly number[],
    d: readonly number[],
    kx: number,
    ky: number,
): number {
    // Everything relative to a, in metres.
    const bx = (b[0] - a[0]) * kx;
    const by = (b[1] - a[1]) * ky;
    const cx = (c[0] - a[0]) * kx;
    const cy = (c[1] - a[1]) * ky;
    const dx = (d[0] - a[0]) * kx;
    const dy = (d[1] - a[1]) * ky;
    const side = (ox: number, oy: number, px: number, py: number, qx: number, qy: number): number =>
        (px - ox) * (qy - oy) - (py - oy) * (qx - ox);
    const d1 = side(cx, cy, dx, dy, 0, 0);
    const d2 = side(cx, cy, dx, dy, bx, by);
    const d3 = side(0, 0, bx, by, cx, cy);
    const d4 = side(0, 0, bx, by, dx, dy);
    if (((d1 > 0 && d2 < 0) || (d1 < 0 && d2 > 0)) && ((d3 > 0 && d4 < 0) || (d3 < 0 && d4 > 0))) return 0;
    /** Point p to the segment u→v. */
    const toSeg = (px: number, py: number, ux: number, uy: number, vx: number, vy: number): number => {
        const ex = vx - ux;
        const ey = vy - uy;
        const l2 = ex * ex + ey * ey;
        const t = l2 > 0 ? Math.max(0, Math.min(1, ((px - ux) * ex + (py - uy) * ey) / l2)) : 0;
        return Math.hypot(px - (ux + t * ex), py - (uy + t * ey));
    };
    return Math.min(
        toSeg(0, 0, cx, cy, dx, dy),
        toSeg(bx, by, cx, cy, dx, dy),
        toSeg(cx, cy, 0, 0, bx, by),
        toSeg(dx, dy, 0, 0, bx, by),
    );
}

/**
 * Metres from the segment a→b ([lon, lat]) to a polygon area: 0 where the
 * segment enters it (an end inside, or any edge crossed), else the nearest
 * approach to any of its rings — holes included. kx / ky as segmentDistanceM.
 */
export function segmentGeometryDistanceM(
    a: readonly number[],
    b: readonly number[],
    geom: Polygon | MultiPolygon,
    kx: number,
    ky: number,
): number {
    if (pointInGeometry(a[0], a[1], geom) || pointInGeometry(b[0], b[1], geom)) return 0;
    let best = Infinity;
    const polys = geom.type === 'Polygon' ? [geom.coordinates] : geom.coordinates;
    for (const poly of polys)
        for (const ring of poly)
            for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
                const m = segmentDistanceM(a, b, ring[j], ring[i], kx, ky);
                if (m < best) best = m;
                if (best === 0) return 0;
            }
    return best;
}

/**
 * Compute the bbox of a polygon/multipolygon geometry as
 * [minLon, minLat, maxLon, maxLat]. Used to skip cells that can't
 * possibly be inside the polygon.
 */
export function geometryBbox(geom: Polygon | MultiPolygon): [number, number, number, number] {
    let minLon = Infinity,
        minLat = Infinity,
        maxLon = -Infinity,
        maxLat = -Infinity;
    const rings = geom.type === 'Polygon' ? [geom.coordinates[0]] : geom.coordinates.map((p) => p[0]);
    for (const ring of rings) {
        for (const [lon, lat] of ring) {
            if (lon < minLon) minLon = lon;
            if (lon > maxLon) maxLon = lon;
            if (lat < minLat) minLat = lat;
            if (lat > maxLat) maxLat = lat;
        }
    }
    return [minLon, minLat, maxLon, maxLat];
}

/**
 * Scanline polygon rasterizer — visit every grid cell strictly inside
 * a Polygon or MultiPolygon, calling `callback(x, y)` per cell.
 *
 * Why this exists
 * ───────────────
 * Pass 1 (DEPARE) was 97% of buildNavGrid in the wild (36.88 s of
 * 38.27 s on a Newport → Brisbane route, May 2026). The previous
 * implementation did one `pointInGeometry()` per cell × per polygon
 * — for a 50-vertex DEPARE polygon covering a 50×50 cell range that's
 * 125,000 ray-cast vertex ops. A scanline fill instead does ~edges
 * per row + cells per row = ~5,000 ops on the same input. The bigger
 * the polygon (more cells, more vertices), the bigger the win.
 *
 * Algorithm
 * ─────────
 * Classic even-odd scanline fill with hole support:
 *   1. For each scanline row y, sweep ALL ring edges (outer + holes)
 *      and collect x-coordinates where the edge crosses lat(y).
 *   2. Sort the crossings ascending. Even-odd parity — between
 *      [0,1], [2,3], [4,5]… is inside; in between is outside.
 *   3. For each "inside" range, snap to cell columns and call the
 *      visitor for each cell whose centre falls inside.
 *
 * Holes work naturally with parity: a hole edge contributes a
 * crossing that flips the inside flag back to outside for that span.
 *
 * Vertex-exactly-on-scanline handling is the strict-greater test
 * `(yi > lat) !== (yj > lat)` — same convention as the existing
 * pointInRing, so the two paths agree on edge cases (cells whose
 * centre lies on a polygon boundary).
 *
 * Cost vs old per-cell pointInGeometry:
 *   • E vertices, R rows, W cells/row, polygon covers ~R×W cells
 *   • Old: R × W × E ray-cast vertex ops
 *   • New: R × E (edge scan) + R × W (fill) ≈ R × (E + W)
 *   • Speedup ≈ W × E / (E + W). For W=E=50: 25×.
 */
export function rasterizePolygonCells(
    grid: { width: number; height: number; minLon: number; minLat: number; dLon: number; dLat: number },
    geom: Polygon | MultiPolygon,
    callback: (x: number, y: number) => void,
): void {
    const polygons: Position[][][] = geom.type === 'Polygon' ? [geom.coordinates] : geom.coordinates;
    const { width, height, minLon, minLat, dLon, dLat } = grid;

    for (const poly of polygons) {
        // Per-polygon row range from the outer ring's lat extent.
        // Inner rings (holes) live entirely inside the outer, so they
        // can't extend the row range.
        const outer = poly[0];
        let minLatPoly = Infinity;
        let maxLatPoly = -Infinity;
        for (let i = 0; i < outer.length; i++) {
            const lat = outer[i][1];
            if (lat < minLatPoly) minLatPoly = lat;
            if (lat > maxLatPoly) maxLatPoly = lat;
        }
        const y0 = Math.max(0, Math.floor((minLatPoly - minLat) / dLat));
        const y1 = Math.min(height - 1, Math.ceil((maxLatPoly - minLat) / dLat));
        if (y1 < y0) continue;

        // Reuse one scratch array per polygon to avoid per-row GC churn.
        const crossings: number[] = [];

        for (let y = y0; y <= y1; y++) {
            const lat = minLat + (y + 0.5) * dLat;
            crossings.length = 0;

            // Collect crossings from outer + holes alike. Even-odd
            // parity below handles hole subtraction without needing
            // an explicit "skip" pass.
            for (const ring of poly) {
                for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
                    const yi = ring[i][1];
                    const yj = ring[j][1];
                    if (yi > lat !== yj > lat) {
                        const xi = ring[i][0];
                        const xj = ring[j][0];
                        const x = ((xj - xi) * (lat - yi)) / (yj - yi) + xi;
                        crossings.push(x);
                    }
                }
            }
            if (crossings.length < 2) continue;
            crossings.sort((a, b) => a - b);

            // Pair-fill: [0..1], [2..3], … are inside spans (even-odd).
            for (let k = 0; k + 1 < crossings.length; k += 2) {
                const lonStart = crossings[k];
                const lonEnd = crossings[k + 1];
                // First column whose cell-centre is ≥ lonStart, last
                // whose centre is ≤ lonEnd. The centre-test is what
                // matches the old per-cell pointInGeometry semantics
                // exactly — we still classify by cell centre, just
                // without paying the ray-cast on each one.
                const xStart = Math.max(0, Math.ceil((lonStart - minLon) / dLon - 0.5));
                const xEnd = Math.min(width - 1, Math.floor((lonEnd - minLon) / dLon - 0.5));
                for (let x = xStart; x <= xEnd; x++) {
                    callback(x, y);
                }
            }
        }
    }
}

export function isNavigable(grid: NavGrid, x: number, y: number): boolean {
    if (x < 0 || y < 0 || x >= grid.width || y >= grid.height) return false;
    return !Number.isNaN(grid.cells[y * grid.width + x]);
}

export function gridToLatLon(grid: NavGrid, x: number, y: number): [number, number] {
    // Cell center
    const lon = grid.minLon + (x + 0.5) * grid.dLon;
    const lat = grid.minLat + (y + 0.5) * grid.dLat;
    return [lon, lat];
}

export function latLonToGrid(grid: NavGrid, lat: number, lon: number): { x: number; y: number } {
    const x = Math.floor((lon - grid.minLon) / grid.dLon);
    const y = Math.floor((lat - grid.minLat) / grid.dLat);
    return { x, y };
}

/**
 * Every grid cell the straight segment a→b ([lon, lat]) touches: a supercover
 * walk (Amanatides–Woo), with both neighbours where the line passes exactly
 * through a cell corner. A fixed-step sampler can step over a corner the line
 * clips for a metre; this cannot (round-2 fix-up review, 2026-10-03: the
 * route's caution reasons missed the cell a 25 m sampler had flagged). Cells
 * off the grid are skipped. The visit order is along the line.
 */
export function forEachCellOnSegment(
    grid: NavGrid,
    a: readonly [number, number],
    b: readonly [number, number],
    visit: (idx: number) => void,
): void {
    const fx0 = (a[0] - grid.minLon) / grid.dLon;
    const fy0 = (a[1] - grid.minLat) / grid.dLat;
    const fx1 = (b[0] - grid.minLon) / grid.dLon;
    const fy1 = (b[1] - grid.minLat) / grid.dLat;
    if (!(Number.isFinite(fx0) && Number.isFinite(fy0) && Number.isFinite(fx1) && Number.isFinite(fy1))) return;
    const at = (x: number, y: number): void => {
        if (x >= 0 && y >= 0 && x < grid.width && y < grid.height) visit(y * grid.width + x);
    };
    let x = Math.floor(fx0);
    let y = Math.floor(fy0);
    const dx = fx1 - fx0;
    const dy = fy1 - fy0;
    const sx = dx > 0 ? 1 : dx < 0 ? -1 : 0;
    const sy = dy > 0 ? 1 : dy < 0 ? -1 : 0;
    const tDx = sx !== 0 ? 1 / Math.abs(dx) : Infinity;
    const tDy = sy !== 0 ? 1 / Math.abs(dy) : Infinity;
    // The line's parameter (0..1) at the next vertical / horizontal cell edge.
    let tx = sx > 0 ? (x + 1 - fx0) * tDx : sx < 0 ? (fx0 - x) * tDx : Infinity;
    let ty = sy > 0 ? (y + 1 - fy0) * tDy : sy < 0 ? (fy0 - y) * tDy : Infinity;
    at(x, y);
    let n = Math.abs(Math.floor(fx1) - x) + Math.abs(Math.floor(fy1) - y);
    while (n > 0) {
        if (Math.abs(tx - ty) <= 1e-9) {
            // Exactly through a corner: it touches both neighbours too.
            at(x + sx, y);
            at(x, y + sy);
            x += sx;
            y += sy;
            tx += tDx;
            ty += tDy;
            n -= 2;
        } else if (tx < ty) {
            x += sx;
            tx += tDx;
            n -= 1;
        } else {
            y += sy;
            ty += tDy;
            n -= 1;
        }
        at(x, y);
    }
}

/**
 * Bresenham's line algorithm. Iterates the cells touched by the line
 * from (x0,y0) to (x1,y1). Used to test whether two cells have an
 * unobstructed straight-line path between them.
 */
export function* bresenhamCells(x0: number, y0: number, x1: number, y1: number): Generator<{ x: number; y: number }> {
    const dx = Math.abs(x1 - x0);
    const dy = Math.abs(y1 - y0);
    const sx = x0 < x1 ? 1 : -1;
    const sy = y0 < y1 ? 1 : -1;
    let err = dx - dy;
    let x = x0;
    let y = y0;
    while (true) {
        yield { x, y };
        if (x === x1 && y === y1) break;
        const e2 = 2 * err;
        if (e2 > -dy) {
            err -= dy;
            x += sx;
        }
        if (e2 < dx) {
            err += dx;
            y += sy;
        }
    }
}

// ── Polyline simplification (Douglas-Peucker) ───────────────────────

/**
 * Perpendicular distance from point P to segment AB, in degrees.
 * Used purely for relative comparison; no need for meters.
 */
export function perpendicularDistanceDeg(p: [number, number], a: [number, number], b: [number, number]): number {
    const dx = b[0] - a[0];
    const dy = b[1] - a[1];
    if (dx === 0 && dy === 0) {
        return Math.hypot(p[0] - a[0], p[1] - a[1]);
    }
    const t = Math.max(0, Math.min(1, ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / (dx * dx + dy * dy)));
    const projX = a[0] + t * dx;
    const projY = a[1] + t * dy;
    return Math.hypot(p[0] - projX, p[1] - projY);
}

/** @internal exported for the douglas-peucker termination regression test. */
export function douglasPeucker(
    points: [number, number][],
    toleranceDeg: number,
    /** Optional land guard: returns true if the straight chord a→b crosses
     *  land. When it does, the span is NOT collapsed — the bend vertices are
     *  kept — so the simplifier can never cut a chord across a canal bank (the
     *  Newport canal-bend corner-clip, 2026-06-18). */
    chordCrossesLand?: (a: [number, number], b: [number, number]) => boolean,
): [number, number][] {
    if (points.length < 3) return points.slice();
    let maxD = 0;
    let idx = 0;
    for (let i = 1; i < points.length - 1; i++) {
        const d = perpendicularDistanceDeg(points[i], points[0], points[points.length - 1]);
        if (d > maxD) {
            maxD = d;
            idx = i;
        }
    }
    // Recurse ONLY on a geometric split. maxD > tol guarantees idx ≥ 1, so both
    // sub-slices strictly shrink and the recursion always terminates. (The land
    // guard must NEVER gate this branch: on a near-straight chord that merely
    // nicks a land cell, maxD is ~0 and idx stays 0, so points.slice(idx) ===
    // points.slice(0) — the same array — and the right branch recurses on itself
    // forever → stack overflow → the engine throws → the passage falls through to
    // the "route too short" bail. That was the 2026-06-18 canal regression.)
    if (maxD > toleranceDeg) {
        const left = douglasPeucker(points.slice(0, idx + 1), toleranceDeg, chordCrossesLand);
        const right = douglasPeucker(points.slice(idx), toleranceDeg, chordCrossesLand);
        return left.slice(0, -1).concat(right);
    }
    // Geometry says collapse to the chord — but never collapse a chord that
    // cuts across a canal bank. Keep every vertex (no recursion, terminates).
    if (chordCrossesLand?.(points[0], points[points.length - 1])) {
        return points.slice();
    }
    return [points[0], points[points.length - 1]];
}

/**
 * Collapse a splice's densify scaffold (round 4, 2026-09-30): near-collinear
 * vertices INSIDE runs of segments that share one state key, Douglas-Peucker
 * per run with the land-guard contract above — a merged chord stands only
 * where `chordFits(a, b, runKey)` says the straight line reads the run's own
 * state (and crosses no land). So a run is never merged across a change of
 * state, and a merged line never reads a different state from the segments
 * it replaces. Returns the new polyline and, per new segment, the index of an
 * original segment of its run (its per-segment facts carry over unchanged).
 *
 * `pinned` (per vertex) marks anchors no merge may remove (round 5,
 * 2026-10-01): a lateral-mark gate crossing. A run is simplified piecewise
 * between its pinned vertices, so the scaffold either side still collapses
 * but the line keeps a point in every gate — Newport's gate 5/6 centre sits
 * 1.2 m off the 7/8 → 3/4 chord, inside the 2.5 m tolerance, and went.
 */
export function collapseStateRuns(
    polyline: readonly [number, number][],
    segKeys: readonly string[],
    toleranceDeg: number,
    chordFits: (a: [number, number], b: [number, number], runKey: string) => boolean,
    pinned?: readonly boolean[],
): { polyline: [number, number][]; fromSeg: number[] } {
    const segCount = polyline.length - 1;
    if (segCount < 2 || segKeys.length !== segCount) {
        return {
            polyline: polyline.map((p) => [p[0], p[1]]),
            fromSeg: Array.from({ length: Math.max(0, segCount) }, (_, i) => i),
        };
    }
    const out: [number, number][] = [[polyline[0][0], polyline[0][1]]];
    const fromSeg: number[] = [];
    let runStart = 0;
    for (let i = 1; i <= segCount; i++) {
        if (i < segCount && segKeys[i] === segKeys[runStart]) continue;
        // Run of segments [runStart, i) → points [runStart, i], simplified
        // piece by piece between its pinned interior vertices.
        const key = segKeys[runStart];
        let pieceStart = runStart;
        for (let v = runStart + 1; v <= i; v++) {
            if (v < i && !pinned?.[v]) continue;
            const pts = polyline.slice(pieceStart, v + 1).map((p) => [p[0], p[1]] as [number, number]);
            const kept = pts.length < 3 ? pts : douglasPeucker(pts, toleranceDeg, (a, b) => !chordFits(a, b, key));
            for (let k = 1; k < kept.length; k++) {
                out.push(kept[k]);
                fromSeg.push(pieceStart);
            }
            pieceStart = v;
        }
        runStart = i;
    }
    return { polyline: out, fromSeg };
}

/** How many buckets wide bboxBuckets' coarse buckets are. */
const BUCKET_COARSE = 16;

/**
 * A bucket grid over bounding boxes ([w, s, e, n]): which items' boxes meet a
 * query box, in the items' own order — the same answer as filtering the whole
 * list, without reading every item. Items whose box spans more than
 * `maxCells` buckets (an overview cell's bands) go in a coarse grid of
 * buckets BUCKET_COARSE times wider (G2, 2026-10-04: Brisbane's cells hold
 * 910 such bands, and every spot asked read them all); wider still, they are
 * always candidates. A query wider than `maxQueryCells` buckets filters the
 * list. For the any-angle string pull (engine/stringPull, 2026-10-03), which
 * reads the chart at thousands of spots along the chords it weighs.
 */
export function bboxBuckets<T>(
    items: readonly T[],
    bboxOf: (item: T) => readonly number[],
    cellDeg = 0.01,
    maxCells = 256,
    maxQueryCells = 4096,
): (box: readonly number[]) => T[] {
    const boxes = items.map(bboxOf);
    const meets = (b: readonly number[], q: readonly number[]): boolean =>
        !(b[2] < q[0] || b[0] > q[2] || b[3] < q[1] || b[1] > q[3]);
    if (items.length === 0) return () => [];
    let lon0 = Infinity;
    let lat0 = Infinity;
    for (const b of boxes) {
        if (b[0] < lon0) lon0 = b[0];
        if (b[1] < lat0) lat0 = b[1];
    }
    const col = (lon: number): number => Math.floor((lon - lon0) / cellDeg);
    const row = (lat: number): number => Math.floor((lat - lat0) / cellDeg);
    const key = (c: number, r: number): number => r * 1_000_003 + c;
    const big: number[] = [];
    const buckets = new Map<number, number[]>();
    const coarse = new Map<number, number[]>();
    // A coarse bucket holds BUCKET_COARSE² buckets (by their own indices, so
    // a box meeting a query shares a coarse bucket with it).
    const up = (v: number): number => Math.floor(v / BUCKET_COARSE);
    const add = (into: Map<number, number[]>, c0: number, c1: number, r0: number, r1: number, i: number): void => {
        for (let r = r0; r <= r1; r++)
            for (let c = c0; c <= c1; c++) {
                const k = key(c, r);
                const list = into.get(k);
                if (list) list.push(i);
                else into.set(k, [i]);
            }
    };
    boxes.forEach((b, i) => {
        const c0 = col(b[0]);
        const c1 = col(b[2]);
        const r0 = row(b[1]);
        const r1 = row(b[3]);
        if (!(Number.isFinite(c0) && Number.isFinite(c1) && Number.isFinite(r0) && Number.isFinite(r1))) {
            big.push(i);
            return;
        }
        if ((c1 - c0 + 1) * (r1 - r0 + 1) <= maxCells) add(buckets, c0, c1, r0, r1, i);
        else if ((up(c1) - up(c0) + 1) * (up(r1) - up(r0) + 1) <= maxCells)
            add(coarse, up(c0), up(c1), up(r0), up(r1), i);
        else big.push(i);
    });
    const seen = new Uint32Array(items.length);
    let stamp = 0;
    return (q) => {
        const c0 = Math.max(col(q[0]), -1);
        const c1 = col(q[2]);
        const r0 = Math.max(row(q[1]), -1);
        const r1 = row(q[3]);
        if ((c1 - c0 + 1) * (r1 - r0 + 1) > maxQueryCells) return items.filter((_, i) => meets(boxes[i], q));
        stamp++;
        if (stamp === 0xffffffff) {
            seen.fill(0);
            stamp = 1;
        }
        const hits: number[] = [];
        const take = (i: number): void => {
            if (seen[i] === stamp) return;
            seen[i] = stamp;
            if (meets(boxes[i], q)) hits.push(i);
        };
        for (const i of big) take(i);
        if (coarse.size > 0)
            for (let r = up(r0); r <= up(r1); r++)
                for (let c = up(c0); c <= up(c1); c++) {
                    const list = coarse.get(key(c, r));
                    if (list) for (const i of list) take(i);
                }
        for (let r = r0; r <= r1; r++)
            for (let c = c0; c <= c1; c++) {
                const list = buckets.get(key(c, r));
                if (list) for (const i of list) take(i);
            }
        hits.sort((x, y) => x - y);
        return hits.map((i) => items[i]);
    };
}
