/**
 * The Pi runs the SAME collision rule (build 126, package 126-04a).
 *
 * The Pi's night watch (pi-cache/src/aisWatch.ts) grades every AIS target with
 * pi-cache/src/collisionRule/collisionRule.ts, which is utils/collisionRule.ts
 * copied VERBATIM under a generated header by
 * pi-cache/scripts/sync-collision-rule.mjs. Two rules that drifted apart would
 * mean a phone and a Pi aboard the same boat disagreeing about the same ship,
 * so any change to the app's rule without a re-sync fails here (and in the
 * script's own --check).
 *
 * The parity cases (pi-cache/src/collisionRule/parity.fixtures.json) run
 * through the APP module here and through the MIRROR in
 * pi-cache/src/aisWatch.test.mts: both must give the same answers. Fictional
 * ships, worldwide waters (the Solent, the Hauraki Gulf, Chesapeake Bay, Fiji
 * across the antimeridian).
 */
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import * as rule from '../utils/collisionRule';

const read = (relative: string): string => readFileSync(resolve(process.cwd(), relative), 'utf8');

const SOURCE = 'utils/collisionRule.ts';
const MIRROR = 'pi-cache/src/collisionRule/collisionRule.ts';
const STAMP = 'pi-cache/src/collisionRule/syncedFrom.ts';
const SCRIPT = 'pi-cache/scripts/sync-collision-rule.mjs';

/** Exactly what the script writes above the copied source. */
const HEADER = [
    '// GENERATED by pi-cache/scripts/sync-collision-rule.mjs from utils/collisionRule.ts, copied verbatim below.',
    '// Do not edit here: change utils/collisionRule.ts, then run `node pi-cache/scripts/sync-collision-rule.mjs`.',
    '// tests/CollisionRulePiMirror.test.ts and the script --check fail on any difference.',
    '',
    '',
].join('\n');

describe('the Pi copy of the collision rule', () => {
    it('is the app rule, byte for byte, under its generated header', () => {
        const source = read(SOURCE);
        const mirror = read(MIRROR);
        expect(mirror.startsWith(HEADER), 'the mirror starts with the generated header').toBe(true);
        // Not toEqual on two 25 KB strings: say where they part.
        const body = mirror.slice(HEADER.length);
        if (body !== source) {
            let at = 0;
            while (at < body.length && body[at] === source[at]) at += 1;
            const line = source.slice(0, at).split('\n').length;
            throw new Error(`the Pi copy differs from ${SOURCE} at line ${line}: run node ${SCRIPT}`);
        }
        expect(mirror).toBe(HEADER + source);
    });

    it('records the sha256 of the source it copied', () => {
        const sha = createHash('sha256').update(read(SOURCE)).digest('hex');
        const stamp = read(STAMP);
        expect(stamp).toContain(`sha256: '${sha}'`);
        expect(stamp).toContain(`source: '${SOURCE}'`);
        expect(stamp).toMatch(/commit: '[0-9a-f]{8}(-dirty)?'/);
    });

    it('can stay a verbatim copy: the app rule imports nothing', () => {
        const source = read(SOURCE);
        expect(source).not.toMatch(/^\s*import\s/m);
        expect(source).not.toMatch(/^\s*export\s+(?:type\s+)?(?:\*|\{[^}]*\})\s+from\s/m);
        expect(source).not.toMatch(/\brequire\(|import\(/);
    });

    it('is written by a script that refuses an import and can check for drift', () => {
        const script = read(SCRIPT);
        expect(script).toContain("'--check'");
        expect(script).toContain(SOURCE);
        expect(script).toMatch(/refus/i);
    });
});

describe('the latch numbers live in the shared rule (one set for the phone and the Pi)', () => {
    it('COLLISION_RULE.latch carries the encounter latch', () => {
        expect(rule.COLLISION_RULE.latch).toEqual({
            blindAfterMs: 60_000,
            atAnchorBlindAfterMs: 10 * 60_000,
            clearAfterMs: 30_000,
            clearMinPasses: 3,
            settledAfterMs: 3 * 60_000,
            lostHoldAfterCpaMs: 10 * 60_000,
            blindNoticeEveryMs: 30 * 60_000,
        });
        expect(Object.isFrozen(rule.COLLISION_RULE.latch)).toBe(true);
    });

    it('the phone alarm reads them instead of keeping its own', () => {
        const service = read('services/CollisionAlarmService.ts');
        for (const name of [
            'BLIND_AFTER_MS',
            'AT_ANCHOR_BLIND_AFTER_MS',
            'CLEAR_AFTER_MS',
            'CLEAR_MIN_PASSES',
            'SETTLED_AFTER_MS',
            'LOST_HOLD_AFTER_CPA_MS',
            'BLIND_NOTICE_EVERY_MS',
        ]) {
            expect(service, name).not.toMatch(new RegExp(`const ${name} = \\d`));
        }
        expect(service).toContain('COLLISION_RULE.latch');
    });
});

// ── Parity: every case through the APP module ───────────────────────────────

interface ParityCase {
    name: string;
    fn: string;
    expect: unknown;
    [key: string]: unknown;
}

const PARITY = JSON.parse(read('pi-cache/src/collisionRule/parity.fixtures.json')) as { cases: ParityCase[] };

const r3 = (x: unknown) => (typeof x === 'number' ? Math.round(x * 1000) / 1000 : x);

/** The same small runner pi-cache/src/aisWatch.test.mts uses on the mirror. */
function run(c: ParityCase): unknown {
    switch (c.fn) {
        case 'assessCollision': {
            const prefs = rule.sanitiseCollisionPrefs(c.prefs);
            const own = c.own as rule.CollisionOwnShip;
            const target = c.target as rule.CollisionTarget;
            const a = rule.assessCollision(own, target, prefs);
            if (!a) return null;
            return {
                risk: a.risk,
                closeQuarters: a.closeQuarters,
                pair: a.pair,
                alarm: a.alarm,
                rangeOnly: a.rangeOnly,
                reason: a.reason,
                rangeNm: r3(a.rangeNm),
                bearingDeg: r3(a.bearingDeg),
                cpaNm: r3(a.cpaNm),
                tcpaMin: r3(a.tcpaMin),
                opening: rule.collisionOpening(a, prefs),
                settled: rule.collisionSettled(a, own, rule.aisSogKn(target.sogKn)),
                soundsMuted: rule.collisionShouldSound(a, 1e15, 0),
            };
        }
        case 'classifyDistress':
            return rule.classifyDistress(c.evidence as rule.DistressEvidence);
        case 'collisionPairFor':
            return rule.collisionPairFor(c.ownSogKn as number | null, c.previous as rule.CollisionPairName | null);
        case 'aisSogKn':
            return rule.aisSogKn(c.value);
        case 'aisCogDeg':
            return rule.aisCogDeg(c.value);
        case 'aisHeadingDeg':
            return rule.aisHeadingDeg(c.value);
        case 'distressKindOfMmsi':
            return rule.distressKindOfMmsi(c.value);
        default:
            throw new Error(`no runner for ${c.fn}`);
    }
}

describe('parity cases, through the app rule', () => {
    it('cover the encounters the Pi grades all night', () => {
        expect(PARITY.cases.length).toBeGreaterThanOrEqual(30);
        const names = PARITY.cases.map((c) => c.name).join('\n');
        for (const water of ['Solent', 'Hauraki', 'Chesapeake', 'Fiji']) expect(names).toContain(water);
        expect(new Set(PARITY.cases.map((c) => c.fn))).toEqual(
            new Set([
                'assessCollision',
                'classifyDistress',
                'collisionPairFor',
                'aisSogKn',
                'aisCogDeg',
                'aisHeadingDeg',
                'distressKindOfMmsi',
            ]),
        );
    });

    for (const c of PARITY.cases) {
        it(c.name, () => {
            expect(run(c)).toEqual(c.expect);
        });
    }
});
