// @vitest-environment node
/**
 * The lossless cutter, proven against real encoded video.
 *
 * Fixtures are generated by scripts/make-trim-fixtures.sh (needs ffmpeg) and
 * committed small: 130s of test pattern at 640x360 in both codecs the iPhone
 * produces. If the fixtures are absent the suite skips rather than fails, so
 * CI without ffmpeg artifacts stays green — but a machine with them gets the
 * real assertion: cut a minute out of the middle and the streams stay whole.
 */
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

import {
    probeVideoDurationSeconds,
    readContainerBrand,
    remuxVideoLossless,
    trimVideoLossless,
} from '../services/videoTrim';

const fixture = (name: string) => resolve(process.cwd(), 'tests/fixtures', name);
const have = (name: string) => existsSync(fixture(name));

const load = (name: string) => new Blob([readFileSync(fixture(name))]);

describe('trimVideoLossless', () => {
    it.skipIf(!have('trim-h264.mp4'))('cuts a keyframe-snapped minute from h264 mp4', async () => {
        const result = await trimVideoLossless(load('trim-h264.mp4'), 33.7, 60);
        // Snapped BACK to the previous keyframe, never forward past the ask.
        expect(result.actualStartSec).toBeLessThanOrEqual(33.7);
        expect(result.actualStartSec).toBeGreaterThan(30);
        // Proportional size: ~60s out of 130s, so under two-thirds and non-trivial.
        const ratio = result.blob.size / load('trim-h264.mp4').size;
        expect(ratio).toBeGreaterThan(0.3);
        expect(ratio).toBeLessThan(0.66);
        expect(result.blob.type).toBe('video/mp4');
    });

    it.skipIf(!have('trim-hevc.mov'))('cuts HEVC out of a QuickTime container', async () => {
        const result = await trimVideoLossless(load('trim-hevc.mov'), 33.7, 60);
        expect(result.actualStartSec).toBeLessThanOrEqual(33.7);
        expect(result.blob.size).toBeGreaterThan(1_000_000);
        expect(result.blob.type).toBe('video/mp4');
    });

    it.skipIf(!have('trim-h264.mp4'))('a start beyond the end still yields the final window', async () => {
        const result = await trimVideoLossless(load('trim-h264.mp4'), 500, 60);
        // Snap lands on the last keyframe; the cut holds whatever remains.
        expect(result.blob.size).toBeGreaterThan(0);
    });

    it('refuses a file that is not a video, with words rather than a hang', async () => {
        await expect(trimVideoLossless(new Blob([new Uint8Array(4096)]), 0, 60)).rejects.toThrow();
    });
});

describe('remuxVideoLossless', () => {
    it.skipIf(!have('trim-hevc.mov'))('rebrands a QuickTime camera file as a real MP4', async () => {
        const source = load('trim-hevc.mov');
        // Precondition: the fixture really is what an iPhone hands over — a
        // qt-brand container. If ffmpeg ever changes this, the test is void.
        const srcBytes = new Uint8Array(await source.arrayBuffer());
        expect(new TextDecoder().decode(srcBytes.slice(8, 12))).toBe('qt  ');

        const result = await remuxVideoLossless(source);
        const outBytes = new Uint8Array(await result.blob.arrayBuffer());
        // Chrome rejects brand `qt` outright — the whole point of the remux
        // (the public voyage log's crossed-out play button, 2026-08-31).
        expect(new TextDecoder().decode(outBytes.slice(8, 12))).not.toBe('qt  ');
        expect(result.blob.type).toBe('video/mp4');
    });

    it.skipIf(!have('trim-hevc.mov'))('keeps the whole film — same duration, roughly same bytes', async () => {
        const source = new Blob([load('trim-hevc.mov')]);
        const inDuration = await probeVideoDurationSeconds(source);
        const result = await remuxVideoLossless(source);
        const outDuration = await probeVideoDurationSeconds(result.blob);
        expect(inDuration).not.toBeNull();
        expect(outDuration).not.toBeNull();
        // Keyframe snap at 0 keeps frame one; the tail is never cut.
        expect(Math.abs((outDuration ?? 0) - (inDuration ?? 0))).toBeLessThan(1.5);
        // Lossless: no re-encode means no meaningful size change either way.
        const ratio = result.blob.size / source.size;
        expect(ratio).toBeGreaterThan(0.85);
        expect(ratio).toBeLessThan(1.1);
    });
});

describe('readContainerBrand', () => {
    const ftyp = (brand: string): Blob => {
        const bytes = new Uint8Array(32);
        const dv = new DataView(bytes.buffer);
        dv.setUint32(0, 32); // box size
        for (let i = 0; i < 4; i++) bytes[4 + i] = 'ftyp'.charCodeAt(i);
        for (let i = 0; i < 4; i++) bytes[8 + i] = brand.charCodeAt(i);
        return new Blob([bytes]);
    };

    it('names the brand from the first bytes without reading the file', async () => {
        // The whole point: a 296MB DJI reel is classified from 32 bytes,
        // never loaded — the in-memory remux was Jetsam-killing the app on
        // files that never needed it (2026-09-01).
        expect(await readContainerBrand(ftyp('isom'))).toBe('isom');
        expect(await readContainerBrand(ftyp('qt  '))).toBe('qt  ');
        expect(await readContainerBrand(ftyp('mp42'))).toBe('mp42');
    });

    it('returns null for a non-video file rather than guessing', async () => {
        expect(await readContainerBrand(new Blob([new Uint8Array(64)]))).toBeNull();
        expect(await readContainerBrand(new Blob([new Uint8Array(4)]))).toBeNull();
    });

    it.skipIf(!have('trim-hevc.mov'))('agrees with the real fixtures', async () => {
        expect(await readContainerBrand(load('trim-hevc.mov'))).toBe('qt  ');
        expect(await readContainerBrand(load('trim-h264.mp4'))).toBe('isom');
    });
});
