// @vitest-environment node
/**
 * The lossless cutter, proven against real encoded video.
 *
 * Fixtures are generated by scripts/make-trim-fixtures.sh (needs ffmpeg) and
 * committed small: 130s of test pattern at 640x360 in both codecs the iPhone
 * produces. If the fixtures are absent the suite skips rather than fails, so
 * CI without ffmpeg artifacts stays green — but a machine with them gets the
 * real assertion: cut a minute out of the middle and the streams stay whole.
 */
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

import { trimVideoLossless } from '../services/videoTrim';

const fixture = (name: string) => resolve(process.cwd(), 'tests/fixtures', name);
const have = (name: string) => existsSync(fixture(name));

const load = (name: string) => new Blob([readFileSync(fixture(name))]);

describe('trimVideoLossless', () => {
    it.skipIf(!have('trim-h264.mp4'))('cuts a keyframe-snapped minute from h264 mp4', async () => {
        const result = await trimVideoLossless(load('trim-h264.mp4'), 33.7, 60);
        // Snapped BACK to the previous keyframe, never forward past the ask.
        expect(result.actualStartSec).toBeLessThanOrEqual(33.7);
        expect(result.actualStartSec).toBeGreaterThan(30);
        // Proportional size: ~60s out of 130s, so under two-thirds and non-trivial.
        const ratio = result.blob.size / load('trim-h264.mp4').size;
        expect(ratio).toBeGreaterThan(0.3);
        expect(ratio).toBeLessThan(0.66);
        expect(result.blob.type).toBe('video/mp4');
    });

    it.skipIf(!have('trim-hevc.mov'))('cuts HEVC out of a QuickTime container', async () => {
        const result = await trimVideoLossless(load('trim-hevc.mov'), 33.7, 60);
        expect(result.actualStartSec).toBeLessThanOrEqual(33.7);
        expect(result.blob.size).toBeGreaterThan(1_000_000);
        expect(result.blob.type).toBe('video/mp4');
    });

    it.skipIf(!have('trim-h264.mp4'))('a start beyond the end still yields the final window', async () => {
        const result = await trimVideoLossless(load('trim-h264.mp4'), 500, 60);
        // Snap lands on the last keyframe; the cut holds whatever remains.
        expect(result.blob.size).toBeGreaterThan(0);
    });

    it('refuses a file that is not a video, with words rather than a hang', async () => {
        await expect(trimVideoLossless(new Blob([new Uint8Array(4096)]), 0, 60)).rejects.toThrow();
    });
});
