// GENERATED by pi-cache/scripts/sync-collision-rule.mjs. Do not edit.
/** The app commit the Pi's collision rule was copied from, and the sha256 of the source it copied. */
export const COLLISION_RULE_SYNCED_FROM = {
    commit: '558666f0-dirty',
    source: 'utils/collisionRule.ts',
    sha256: '2dbb12ce4a002e51f38167699bb834f5cae631e426908331bfa0387d84a8aadb',
} as const;
