/**
 * MaintenancePdfService — PDF export for vessel maintenance.
 *
 * Two templates:
 *   A) Engine Room Clipboard: blank checklist of active/upcoming tasks
 *   B) Formal Service Record: completed history ledger
 *
 * Uses jsPDF for generation + @capacitor/share for native share sheet.
 * Falls back to browser download on web.
 */
import jsPDF from 'jspdf';
import { Filesystem, Directory } from '@capacitor/filesystem';
import { Share } from '@capacitor/share';
import { MaintenanceService, calculateStatus, sortByUrgency } from './MaintenanceService';
import type { MaintenanceTask, MaintenanceHistory } from '../types';

// ── Shared Helpers ──────────────────────────────────────────────

function formatDate(iso: string | null): string {
    if (!iso) return '—';
    return new Date(iso).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
}

function formatCurrency(val: number | null): string {
    if (val === null || val === undefined || val === 0) return '—';
    return `$${val.toFixed(2)}`;
}

// ── TEMPLATE A: Engine Room Clipboard ───────────────────────────

function generateChecklistHtml(
    tasks: MaintenanceTask[],
    engineHours: number,
    vesselName: string,
): string {
    const now = new Date();
    const dateStr = now.toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' });

    const sorted = sortByUrgency(tasks.map(t => calculateStatus(t, engineHours)));

    const rows = sorted.map(task => {
        const dueCol = task.trigger_type === 'engine_hours'
            ? `${task.next_due_hours?.toLocaleString() ?? '—'} hrs`
            : task.next_due_date ? formatDate(task.next_due_date) : '—';

        const statusDot = task.status === 'red' ? '🔴' : task.status === 'yellow' ? '🟡' : '🟢';

        return `
            <tr>
                <td style="width:32px;text-align:center;font-size:18px;padding:8px 4px;">☐</td>
                <td style="padding:8px 6px;font-weight:700;font-size:11px;">${statusDot} ${escapeHtml(task.title)}</td>
                <td style="padding:8px 6px;text-align:center;font-size:10px;white-space:nowrap;">${dueCol}</td>
                <td style="padding:8px 6px;font-size:10px;border-bottom:1px solid #ccc;min-width:160px;">&nbsp;</td>
            </tr>`;
    }).join('\n');

    return `<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        * { margin:0; padding:0; box-sizing:border-box; }
        body { font-family: -apple-system, 'Helvetica Neue', Arial, sans-serif; color:#1a1a2e; padding:24px; }
        .header { border-bottom:3px solid #0f4c81; padding-bottom:12px; margin-bottom:16px; }
        .header h1 { font-size:18px; font-weight:900; color:#0f4c81; letter-spacing:0.05em; }
        .header .meta { font-size:10px; color:#666; margin-top:4px; }
        table { width:100%; border-collapse:collapse; font-size:11px; }
        thead th { background:#0f4c81; color:white; padding:8px 6px; text-align:left; font-size:9px; font-weight:800; text-transform:uppercase; letter-spacing:0.1em; }
        tbody tr { border-bottom:1px solid #eee; }
        tbody tr:nth-child(even) { background:#f8f9fa; }
        .footer { margin-top:24px; border-top:1px solid #ddd; padding-top:8px; font-size:8px; color:#999; text-align:center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>⚓ VESSEL MAINTENANCE CHECKLIST</h1>
        <div class="meta">
            <strong>${escapeHtml(vesselName)}</strong> &nbsp;|&nbsp; ${dateStr} &nbsp;|&nbsp; Engine Hours: <strong>${engineHours.toLocaleString()}</strong>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width:32px;text-align:center;">✓</th>
                <th>Task</th>
                <th style="text-align:center;">Next Due</th>
                <th>Notes / Hours at Completion</th>
            </tr>
        </thead>
        <tbody>
            ${rows}
        </tbody>
    </table>

    <div class="footer">
        Generated by Thalassa Marine Weather — ${dateStr}
    </div>
</body>
</html>`;
}

// ── TEMPLATE B: Formal Service Record ───────────────────────────

function generateServiceHistoryHtml(
    history: (MaintenanceHistory & { taskTitle?: string; taskCategory?: string })[],
    vesselName: string,
): string {
    const now = new Date();
    const dateStr = now.toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' });

    const rows = history.map(h => `
        <tr>
            <td style="padding:8px 6px;font-size:10px;white-space:nowrap;">${formatDate(h.completed_at)}</td>
            <td style="padding:8px 6px;font-weight:700;font-size:11px;">${escapeHtml(h.taskTitle || 'Unknown Task')}</td>
            <td style="padding:8px 6px;text-align:center;font-size:10px;">${h.engine_hours_at_service?.toLocaleString() ?? '—'}</td>
            <td style="padding:8px 6px;font-size:10px;">${escapeHtml(h.notes || '—')}</td>
            <td style="padding:8px 6px;text-align:right;font-size:10px;">${formatCurrency(h.cost)}</td>
        </tr>`
    ).join('\n');

    const totalCost = history.reduce((sum, h) => sum + (h.cost || 0), 0);

    return `<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        * { margin:0; padding:0; box-sizing:border-box; }
        body { font-family: -apple-system, 'Helvetica Neue', Arial, sans-serif; color:#1a1a2e; padding:24px; }
        .header { border-bottom:3px solid #0f4c81; padding-bottom:12px; margin-bottom:16px; }
        .header h1 { font-size:18px; font-weight:900; color:#0f4c81; letter-spacing:0.05em; }
        .header .meta { font-size:10px; color:#666; margin-top:4px; }
        table { width:100%; border-collapse:collapse; font-size:11px; }
        thead th { background:#0f4c81; color:white; padding:8px 6px; text-align:left; font-size:9px; font-weight:800; text-transform:uppercase; letter-spacing:0.1em; }
        tbody tr { border-bottom:1px solid #eee; }
        tbody tr:nth-child(even) { background:#f8f9fa; }
        .total-row { font-weight:900; background:#e3f2fd !important; }
        .footer { margin-top:24px; border-top:1px solid #ddd; padding-top:8px; font-size:8px; color:#999; text-align:center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>📋 OFFICIAL VESSEL SERVICE HISTORY</h1>
        <div class="meta">
            <strong>${escapeHtml(vesselName)}</strong> &nbsp;|&nbsp; Generated: ${dateStr} &nbsp;|&nbsp; Entries: <strong>${history.length}</strong>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date Completed</th>
                <th>Task Performed</th>
                <th style="text-align:center;">Engine Hrs</th>
                <th>Notes / Condition</th>
                <th style="text-align:right;">Cost</th>
            </tr>
        </thead>
        <tbody>
            ${rows}
            ${totalCost > 0 ? `
            <tr class="total-row">
                <td colspan="4" style="padding:8px 6px;text-align:right;font-size:11px;">TOTAL EXPENDITURE</td>
                <td style="padding:8px 6px;text-align:right;font-size:11px;">${formatCurrency(totalCost)}</td>
            </tr>` : ''}
        </tbody>
    </table>

    <div class="footer">
        Generated by Thalassa Marine Weather — ${dateStr}
    </div>
</body>
</html>`;
}

// ── PDF Generation & Share ──────────────────────────────────────

/**
 * Generate a PDF from an HTML string using jsPDF and share via native sheet.
 */
async function generateAndSharePdf(html: string, filename: string): Promise<void> {
    const safeName = filename.endsWith('.pdf') ? filename : `${filename}.pdf`;

    // Use jsPDF with html2canvas-like approach
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
    });

    // Render HTML into PDF using jsPDF's html() method
    await new Promise<void>((resolve, reject) => {
        doc.html(html, {
            callback: () => resolve(),
            x: 0,
            y: 0,
            width: 210,  // A4 width in mm
            windowWidth: 800,
            autoPaging: 'text',
        });
    });

    // Get PDF as base64
    const pdfBase64 = doc.output('datauristring').split(',')[1];

    try {
        // Write to cache directory
        const writeResult = await Filesystem.writeFile({
            path: safeName,
            data: pdfBase64,
            directory: Directory.Cache,
        });

        // Trigger native share sheet
        await Share.share({
            title: safeName,
            url: writeResult.uri,
            dialogTitle: 'Export Maintenance Report',
        });
    } catch (err: unknown) {
        const errMsg = err instanceof Error ? err.message : '';
        if (errMsg?.includes('cancel') || errMsg?.includes('dismissed')) {
            return; // User cancelled share sheet — not an error
        }

        // Fallback: browser download
        console.warn('Native share unavailable, falling back to browser download');
        const blob = doc.output('blob');
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = safeName;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }
}

// ── Public API ──────────────────────────────────────────────────

/**
 * Export a blank maintenance checklist PDF (Template A).
 * For printing and taking to the engine room.
 */
export async function exportChecklist(
    engineHours: number,
    vesselName: string,
): Promise<void> {
    const tasks = await MaintenanceService.getTasks();
    const html = generateChecklistHtml(tasks, engineHours, vesselName);
    const dateSlug = new Date().toISOString().slice(0, 10);
    await generateAndSharePdf(html, `Maintenance_Checklist_${dateSlug}.pdf`);
}

/**
 * Export the formal service history PDF (Template B).
 * A permanent ledger of all completed maintenance work.
 */
export async function exportServiceHistory(
    vesselName: string,
): Promise<void> {
    // Fetch history + join with task titles
    const [history, tasks] = await Promise.all([
        MaintenanceService.getAllHistory(500),
        MaintenanceService.getAllTasks(),
    ]);

    const taskMap = new Map(tasks.map(t => [t.id, t]));
    const enriched = history.map(h => ({
        ...h,
        taskTitle: taskMap.get(h.task_id)?.title,
        taskCategory: taskMap.get(h.task_id)?.category,
    }));

    const html = generateServiceHistoryHtml(enriched, vesselName);
    const dateSlug = new Date().toISOString().slice(0, 10);
    await generateAndSharePdf(html, `Service_History_${dateSlug}.pdf`);
}

// ── HTML Escape ─────────────────────────────────────────────────

function escapeHtml(str: string): string {
    return str
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#039;');
}
