/**
 * PassageBriefService — Generate shareable passage briefings.
 *
 * Creates a structured passage brief from the active route data,
 * formatted for sharing via the iOS share sheet (WhatsApp, iMessage,
 * Email, AirDrop).
 *
 * Two output modes:
 *   - Plain text: compact, messaging-app-friendly
 *   - HTML: rich, email/PDF-friendly
 */

import { createLogger } from '../utils/createLogger';

const log = createLogger('PassageBrief');

// ── Types ──

export interface PassageBriefData {
    routeName: string;
    origin: { name: string; lat: number; lon: number };
    destination: { name: string; lat: number; lon: number };
    viaWaypoints?: { name: string; lat: number; lon: number }[];
    departureTime: string;
    totalDistanceNM: number;
    estimatedDuration: number; // hours
    speed: number; // knots
    vesselName?: string;
    vesselType?: string;
    turnWaypoints?: {
        name: string;
        lat: number;
        lon: number;
        tws?: number;
        bng?: number;
    }[];
    isochroneNM?: number;
    /** Tide predictions for departure port */
    departureTides?: { time: string; type: string; height: number }[];
    /** Tide predictions for arrival port */
    arrivalTides?: { time: string; type: string; height: number }[];
}

export interface PassageBrief {
    title: string;
    generatedAt: string;
    data: PassageBriefData;
    textVersion: string;
    htmlVersion: string;
}

// ── Main API ──

/**
 * Generate a complete passage brief from route data.
 */
export function generatePassageBrief(data: PassageBriefData): PassageBrief {
    const title = `${data.origin.name} → ${data.destination.name}`;
    const generatedAt = new Date().toISOString();

    log.info(`[Brief] Generating: ${title} (${data.totalDistanceNM} NM)`);

    return {
        title,
        generatedAt,
        data,
        textVersion: formatBriefAsText(data),
        htmlVersion: formatBriefAsHTML(data),
    };
}

// ── Text Formatter (WhatsApp / iMessage) ──

function formatBriefAsText(data: PassageBriefData): string {
    const lines: string[] = [];

    // Header
    lines.push(`⛵ PASSAGE BRIEF`);
    lines.push(`━━━━━━━━━━━━━━━━━━`);
    if (data.vesselName) {
        lines.push(`🚢 ${data.vesselName}${data.vesselType ? ` (${data.vesselType})` : ''}`);
    }
    lines.push('');

    // Route
    lines.push(`📍 ROUTE`);
    lines.push(`  From: ${data.origin.name}`);
    lines.push(`    ${formatDMS(data.origin.lat, data.origin.lon)}`);
    if (data.viaWaypoints && data.viaWaypoints.length > 0) {
        lines.push(`  Via:`);
        data.viaWaypoints.forEach((wp, i) => {
            lines.push(`    ${i + 1}. ${wp.name} (${wp.lat.toFixed(4)}, ${wp.lon.toFixed(4)})`);
        });
    }
    lines.push(`  To: ${data.destination.name}`);
    lines.push(`    ${formatDMS(data.destination.lat, data.destination.lon)}`);
    lines.push('');

    // Stats
    lines.push(`📏 PASSAGE DATA`);
    lines.push(`  Distance: ${data.totalDistanceNM.toFixed(0)} NM`);
    lines.push(`  ETA Duration: ${formatDuration(data.estimatedDuration)}`);
    lines.push(`  Speed: ${data.speed} kts`);
    lines.push(`  Departure: ${formatDateTime(data.departureTime)}`);

    const arrivalTime = new Date(new Date(data.departureTime).getTime() + data.estimatedDuration * 3600_000);
    lines.push(`  Estimated Arrival: ${formatDateTime(arrivalTime.toISOString())}`);
    lines.push('');

    // Waypoints
    if (data.turnWaypoints && data.turnWaypoints.length > 0) {
        lines.push(`🧭 WAYPOINTS`);
        data.turnWaypoints.forEach((wp, i) => {
            const wind = wp.tws !== undefined ? ` | TWS ${wp.tws.toFixed(0)} kts` : '';
            const brg = wp.bng !== undefined ? ` | BRG ${Math.round(wp.bng)}°` : '';
            lines.push(
                `  ${i + 1}. ${wp.name || `WP${i + 1}`} (${wp.lat.toFixed(4)}, ${wp.lon.toFixed(4)})${wind}${brg}`,
            );
        });
        lines.push('');
    }

    // Tide info
    const depTime = new Date(data.departureTime);
    const arrTime = new Date(depTime.getTime() + data.estimatedDuration * 3600_000);
    const depTideSummary = data.departureTides?.length
        ? formatTideSummaryText(data.departureTides, depTime, data.origin.name)
        : null;
    const arrTideSummary = data.arrivalTides?.length
        ? formatTideSummaryText(data.arrivalTides, arrTime, data.destination.name)
        : null;

    if (depTideSummary || arrTideSummary) {
        lines.push(`🌊 TIDES`);
        if (depTideSummary) lines.push(depTideSummary);
        if (arrTideSummary) lines.push(arrTideSummary);
        lines.push('');
    }

    // Footer
    lines.push(`━━━━━━━━━━━━━━━━━━`);
    lines.push(`Generated by Thalassa Marine Weather`);
    lines.push(`${formatDateTime(new Date().toISOString())}`);

    return lines.join('\n');
}

// ── HTML Formatter (Email / PDF) ──

function formatBriefAsHTML(data: PassageBriefData): string {
    const arrivalTime = new Date(new Date(data.departureTime).getTime() + data.estimatedDuration * 3600_000);

    const waypointRows = (data.turnWaypoints || [])
        .map(
            (wp, i) => `
        <tr>
            <td style="padding:6px 12px;border-bottom:1px solid #1e293b;color:#94a3b8;font-size:12px;">${i + 1}</td>
            <td style="padding:6px 12px;border-bottom:1px solid #1e293b;color:#f1f5f9;font-size:12px;font-weight:600;">${wp.name || `WP${i + 1}`}</td>
            <td style="padding:6px 12px;border-bottom:1px solid #1e293b;color:#94a3b8;font-size:11px;font-family:monospace;">${wp.lat.toFixed(4)}, ${wp.lon.toFixed(4)}</td>
            <td style="padding:6px 12px;border-bottom:1px solid #1e293b;color:#38bdf8;font-size:12px;">${wp.tws !== undefined ? `${wp.tws.toFixed(0)} kts` : '—'}</td>
        </tr>`,
        )
        .join('');

    const viaSection =
        data.viaWaypoints && data.viaWaypoints.length > 0
            ? `<p style="color:#fbbf24;font-size:12px;margin:4px 0 0;">Via: ${data.viaWaypoints.map((wp) => wp.name).join(' → ')}</p>`
            : '';

    return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Passage Brief: ${data.origin.name} → ${data.destination.name}</title>
</head>
<body style="margin:0;padding:0;background:#0f172a;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
<div style="max-width:600px;margin:0 auto;padding:24px;">

<!-- Header -->
<div style="background:linear-gradient(135deg,#0f172a 0%,#1e293b 100%);border:1px solid rgba(255,255,255,0.08);border-radius:16px;padding:24px;margin-bottom:16px;">
    <div style="display:flex;align-items:center;gap:8px;margin-bottom:12px;">
        <span style="font-size:24px;">⛵</span>
        <div>
            <h1 style="margin:0;color:#f1f5f9;font-size:18px;font-weight:800;letter-spacing:0.5px;">PASSAGE BRIEF</h1>
            ${data.vesselName ? `<p style="margin:2px 0 0;color:#64748b;font-size:11px;">🚢 ${data.vesselName}${data.vesselType ? ` • ${data.vesselType}` : ''}</p>` : ''}
        </div>
    </div>

    <!-- Route -->
    <div style="background:rgba(255,255,255,0.03);border-radius:12px;padding:16px;margin-bottom:12px;">
        <div style="display:flex;align-items:center;gap:8px;margin-bottom:8px;">
            <span style="display:inline-block;padding:3px 8px;background:rgba(16,185,129,0.1);border:1px solid rgba(16,185,129,0.2);border-radius:6px;color:#34d399;font-size:11px;font-weight:700;">${data.origin.name}</span>
            <span style="color:#475569;font-size:14px;">→</span>
            <span style="display:inline-block;padding:3px 8px;background:rgba(239,68,68,0.1);border:1px solid rgba(239,68,68,0.2);border-radius:6px;color:#f87171;font-size:11px;font-weight:700;">${data.destination.name}</span>
        </div>
        ${viaSection}
    </div>

    <!-- Stats Grid -->
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;">
        <div style="background:rgba(56,189,248,0.08);border:1px solid rgba(56,189,248,0.15);border-radius:10px;padding:12px;text-align:center;">
            <p style="margin:0;color:#64748b;font-size:9px;text-transform:uppercase;letter-spacing:1px;">Distance</p>
            <p style="margin:4px 0 0;color:#38bdf8;font-size:18px;font-weight:800;">${data.totalDistanceNM.toFixed(0)} NM</p>
        </div>
        <div style="background:rgba(251,191,36,0.08);border:1px solid rgba(251,191,36,0.15);border-radius:10px;padding:12px;text-align:center;">
            <p style="margin:0;color:#64748b;font-size:9px;text-transform:uppercase;letter-spacing:1px;">Duration</p>
            <p style="margin:4px 0 0;color:#fbbf24;font-size:18px;font-weight:800;">${formatDuration(data.estimatedDuration)}</p>
        </div>
        <div style="background:rgba(16,185,129,0.08);border:1px solid rgba(16,185,129,0.15);border-radius:10px;padding:12px;text-align:center;">
            <p style="margin:0;color:#64748b;font-size:9px;text-transform:uppercase;letter-spacing:1px;">Departure</p>
            <p style="margin:4px 0 0;color:#34d399;font-size:13px;font-weight:700;">${formatDateTime(data.departureTime)}</p>
        </div>
        <div style="background:rgba(239,68,68,0.08);border:1px solid rgba(239,68,68,0.15);border-radius:10px;padding:12px;text-align:center;">
            <p style="margin:0;color:#64748b;font-size:9px;text-transform:uppercase;letter-spacing:1px;">ETA</p>
            <p style="margin:4px 0 0;color:#f87171;font-size:13px;font-weight:700;">${formatDateTime(arrivalTime.toISOString())}</p>
        </div>
    </div>
</div>

${
    waypointRows
        ? `
<!-- Waypoints -->
<div style="background:linear-gradient(135deg,#0f172a 0%,#1e293b 100%);border:1px solid rgba(255,255,255,0.08);border-radius:16px;padding:16px;margin-bottom:16px;">
    <h2 style="margin:0 0 12px;color:#e2e8f0;font-size:13px;font-weight:800;text-transform:uppercase;letter-spacing:1px;">🧭 Waypoints</h2>
    <table style="width:100%;border-collapse:collapse;">
        <thead>
            <tr>
                <th style="padding:6px 12px;text-align:left;color:#475569;font-size:10px;text-transform:uppercase;border-bottom:1px solid #334155;">#</th>
                <th style="padding:6px 12px;text-align:left;color:#475569;font-size:10px;text-transform:uppercase;border-bottom:1px solid #334155;">Name</th>
                <th style="padding:6px 12px;text-align:left;color:#475569;font-size:10px;text-transform:uppercase;border-bottom:1px solid #334155;">Position</th>
                <th style="padding:6px 12px;text-align:left;color:#475569;font-size:10px;text-transform:uppercase;border-bottom:1px solid #334155;">Wind</th>
            </tr>
        </thead>
        <tbody>
            ${waypointRows}
        </tbody>
    </table>
</div>`
        : ''
}

${
    data.departureTides?.length || data.arrivalTides?.length
        ? `
<!-- Tides -->
<div style="background:linear-gradient(135deg,#0f172a 0%,#1e293b 100%);border:1px solid rgba(255,255,255,0.08);border-radius:16px;padding:16px;margin-bottom:16px;">
    <h2 style="margin:0 0 12px;color:#e2e8f0;font-size:13px;font-weight:800;text-transform:uppercase;letter-spacing:1px;">🌊 Tides</h2>
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;">
        ${
            data.departureTides?.length
                ? `<div style="background:rgba(16,185,129,0.08);border:1px solid rgba(16,185,129,0.15);border-radius:10px;padding:12px;">
                    <p style="margin:0;color:#64748b;font-size:9px;text-transform:uppercase;letter-spacing:1px;">Departure — ${data.origin.name}</p>
                    ${formatTideSummaryHTML(data.departureTides, new Date(data.departureTime))}
                   </div>`
                : ''
        }
        ${
            data.arrivalTides?.length
                ? `<div style="background:rgba(239,68,68,0.08);border:1px solid rgba(239,68,68,0.15);border-radius:10px;padding:12px;">
                    <p style="margin:0;color:#64748b;font-size:9px;text-transform:uppercase;letter-spacing:1px;">Arrival — ${data.destination.name}</p>
                    ${formatTideSummaryHTML(data.arrivalTides, new Date(new Date(data.departureTime).getTime() + data.estimatedDuration * 3600_000))}
                   </div>`
                : ''
        }
    </div>
</div>`
        : ''
}

<!-- Footer -->
<div style="text-align:center;padding:16px;">
    <p style="margin:0;color:#475569;font-size:10px;">Generated by Thalassa Marine Weather</p>
    <p style="margin:4px 0 0;color:#334155;font-size:9px;">${formatDateTime(new Date().toISOString())}</p>
</div>

</div>
</body>
</html>`;
}

// ── Helpers ──

function formatDMS(lat: number, lon: number): string {
    const fmtCoord = (value: number, pos: string, neg: string): string => {
        const abs = Math.abs(value);
        const deg = Math.floor(abs);
        const min = ((abs - deg) * 60).toFixed(1);
        return `${deg}°${min}'${value >= 0 ? pos : neg}`;
    };
    return `${fmtCoord(lat, 'N', 'S')} ${fmtCoord(lon, 'E', 'W')}`;
}

function formatDuration(hours: number): string {
    if (hours < 24) return `${hours.toFixed(1)}h`;
    const days = Math.floor(hours / 24);
    const remainingHours = Math.round(hours % 24);
    return `${days}d ${remainingHours}h`;
}

function formatDateTime(iso: string): string {
    try {
        const d = new Date(iso);
        return d.toLocaleString('en-AU', {
            weekday: 'short',
            day: 'numeric',
            month: 'short',
            hour: '2-digit',
            minute: '2-digit',
            hour12: false,
        });
    } catch {
        return iso;
    }
}

/**
 * Get the nearest tides to a reference time (before and after).
 * Returns up to 4 tide events: 2 before and 2 after the reference.
 */
function getNearestTides(
    tides: { time: string; type: string; height: number }[],
    refTime: Date,
): { time: string; type: string; height: number; delta: number }[] {
    const refMs = refTime.getTime();
    const sorted = [...tides]
        .map((t) => ({ ...t, delta: new Date(t.time).getTime() - refMs }))
        .sort((a, b) => Math.abs(a.delta) - Math.abs(b.delta));
    return sorted.slice(0, 4);
}

function formatTideSummaryText(
    tides: { time: string; type: string; height: number }[],
    refTime: Date,
    portName: string,
): string {
    const nearest = getNearestTides(tides, refTime);
    if (nearest.length === 0) return '';

    const lines: string[] = [];
    lines.push(`  ${portName}:`);
    nearest.forEach((t) => {
        const icon = t.type.toLowerCase().includes('high') ? '▲' : '▼';
        const label = t.type.toLowerCase().includes('high') ? 'HIGH' : 'LOW';
        const timeStr = formatDateTime(t.time);
        const deltaHrs = Math.abs(t.delta / 3600_000).toFixed(1);
        const beforeAfter = t.delta < 0 ? 'before' : 'after';
        lines.push(`    ${icon} ${label} ${t.height.toFixed(1)}m @ ${timeStr} (${deltaHrs}h ${beforeAfter})`);
    });
    return lines.join('\n');
}

function formatTideSummaryHTML(tides: { time: string; type: string; height: number }[], refTime: Date): string {
    const nearest = getNearestTides(tides, refTime);
    if (nearest.length === 0) return '<p style="color:#94a3b8;font-size:11px;">No data</p>';

    return nearest
        .map((t) => {
            const isHigh = t.type.toLowerCase().includes('high');
            const icon = isHigh ? '▲' : '▼';
            const color = isHigh ? '#38bdf8' : '#94a3b8';
            const label = isHigh ? 'HIGH' : 'LOW';
            const timeStr = formatDateTime(t.time);
            const deltaHrs = Math.abs(t.delta / 3600_000).toFixed(1);
            const beforeAfter = t.delta < 0 ? 'before' : 'after';
            return `<p style="margin:4px 0;color:${color};font-size:11px;">${icon} <strong>${label}</strong> ${t.height.toFixed(1)}m @ ${timeStr} <span style="color:#64748b;font-size:10px;">(${deltaHrs}h ${beforeAfter})</span></p>`;
        })
        .join('');
}
