/**
 * Barrel re-export — all icons split by category.
 * Consumer imports (`from './Icons'`) continue working unchanged.
 */
export {
    WindIcon,
    WaveIcon,
    TideCurveIcon,
    SunIcon,
    MoonIcon,
    CloudIcon,
    RainIcon,
    DropletIcon,
    ThermometerIcon,
    SunriseIcon,
    SunsetIcon,
    WaterIcon,
    ThunderstormIcon,
    PartlyCloudyIcon,
    CycloneIcon,
    LightningBoltIcon,
} from './icons/WeatherIcons';

export {
    CompassIcon,
    MapPinIcon,
    RouteIcon,
    MapIcon,
    ArrowRightIcon,
    ArrowUpIcon,
    ArrowDownIcon,
    ChevronLeftIcon,
    CrosshairIcon,
    FlagIcon,
} from './icons/NavigationIcons';

export {
    SearchIcon,
    EyeIcon,
    BellIcon,
    XIcon,
    CheckIcon,
    GearIcon,
    StarIcon,
    ClockIcon,
    TrashIcon,
    MinusIcon,
    PlusSquareIcon,
    AlertTriangleIcon,
    QuoteIcon,
    LockIcon,
    DiamondIcon,
    ShareIcon,
    BugIcon,
    PhoneIcon,
    GripIcon,
    CheckCircleIcon,
    CartIcon,
    PackageIcon,
    WrenchIcon,
    RefreshIcon,
    MuteIcon,
    EditIcon,
    SendIcon,
    DownloadIcon,
    ClipboardIcon,
    ProhibitedIcon,
    RadioIcon,
    SosIcon,
    SparklesIcon,
    CarIcon,
    WalkIcon,
    CalendarGridIcon,
    UsersIcon,
    LifeBuoyIcon,
    DeviceIcon,
} from './icons/UIIcons';

export {
    BoatIcon,
    SailBoatIcon,
    PowerBoatIcon,
    AnchorIcon,
    ShipWheelIcon,
    RadioTowerIcon,
    ServerIcon,
    CalendarIcon,
    GaugeIcon,
    PlayIcon,
    StopIcon,
    SpeakerWaveIcon,
    FuelIcon,
    FoodIcon,
    ChatIcon,
} from './icons/MaritimeIcons';
