// GENERATED by pi-cache/scripts/sync-router-engine.mjs. Do not edit.
/** The app commit the Pi's routing engine was copied from, and a digest of the copied sources. */
export const ROUTER_ENGINE_SYNCED_FROM = {
    commit: '4d2babdd',
    modules: 35,
    sourceDigest: '22ac8d777db2c6e5dafdaa782bbf7212a58e027d084af577c8a720a71a9ad8d8',
} as const;
