// GENERATED by pi-cache/scripts/sync-router-engine.mjs. Do not edit.
/** The app commit the Pi's routing engine was copied from, and a digest of the copied sources. */
export const ROUTER_ENGINE_SYNCED_FROM = {
    commit: '37a84b23',
    modules: 35,
    sourceDigest: '91655ce00aa584960bb00eb26b213b19342c70f05c579431d8036bb2d0836954',
} as const;
