// GENERATED by pi-cache/scripts/sync-router-engine.mjs. Do not edit.
/** The app commit the Pi's routing engine was copied from, and a digest of the copied sources. */
export const ROUTER_ENGINE_SYNCED_FROM = {
    commit: 'a03bfa74',
    modules: 35,
    sourceDigest: 'f21818ec9a502b218d4f3c2a9cb389f463a3e7fc9ee3dc26ad5458fa53094381',
} as const;
