
const https = require('https');
const fs = require('fs');
const path = require('path');

const url = 'https://raw.githubusercontent.com/mwgg/Airports/master/airports.json';
const outputPath = path.join(__dirname, '../services/AirportDatabase.ts');

console.log('Fetching Airport Data...');

https.get(url, (res) => {
    let data = '';

    res.on('data', (chunk) => {
        data += chunk;
    });

    res.on('end', () => {
        try {
            console.log('Parsing JSON...');
            const airports = JSON.parse(data);

            // Filter: Must have valid IATA (3 chars) and ICAO (4 chars)
            // This effectively filters out small GA strips and heliports
            const filtered = Object.values(airports).filter(a =>
                a.iata && a.iata.length === 3 &&
                a.icao && a.icao.length === 4
            ).map(a => ({
                icao: a.icao,
                iata: a.iata,
                name: a.name,
                lat: a.lat,
                lon: a.lon,
                city: a.city,
                country: a.country
            }));

            console.log(`Found ${filtered.length} Major/Medium Airports.`);

            const fileContent = `
// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by scripts/buildAirportDb.js
// Source: mwgg/Airports (Filtered for IATA codes)

export interface Airport {
    icao: string;
    iata: string;
    name: string;
    lat: number;
    lon: number;
    city: string;
    country: string;
}

export const AIRPORTS: Airport[] = ${JSON.stringify(filtered, null, 2)};

export const findNearestAirport = (lat: number, lon: number): Airport | null => {
    let nearest: Airport | null = null;
    let minDist = Infinity;

    for (const airport of AIRPORTS) {
        // Simple Euclidean distance (accurate enough for finding finding 'closest')
        // Optimizing for speed over Haversine precision for the initial scan
        const dist = Math.pow(airport.lat - lat, 2) + Math.pow(airport.lon - lon, 2);
        
        if (dist < minDist) {
            minDist = dist;
            nearest = airport;
        }
    }
    return nearest;
};
`;

            fs.writeFileSync(outputPath, fileContent);
            console.log(`Successfully wrote database to ${outputPath}`);

        } catch (e) {
            console.error('Error parsing/writing:', e);
            process.exit(1);
        }
    });

}).on('error', (err) => {
    console.error('Error fetching data:', err);
    process.exit(1);
});
