-- Canonicalise the Guardian broadcast RPC after older production installs
-- retained a pre-hardening overload with p_lat/p_lon/p_data argument names.
-- PostgREST resolves RPC calls by argument name, so the stale overload made
-- the current app's lat/lon/alert_data call fail before reaching SQL.

DROP FUNCTION IF EXISTS public.broadcast_guardian_alert(
    UUID, TEXT, TEXT, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION, JSONB
);
DROP FUNCTION IF EXISTS public.broadcast_guardian_alert(
    UUID, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, TEXT, JSONB
);

CREATE FUNCTION public.broadcast_guardian_alert(
    sender_user_id UUID,
    p_alert_type TEXT,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    radius_nm DOUBLE PRECISION DEFAULT 5,
    p_title TEXT DEFAULT '',
    p_body TEXT DEFAULT '',
    alert_data JSONB DEFAULT '{}'::jsonb
)
RETURNS INTEGER
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    alert_id UUID;
    recipient RECORD;
    notify_count INTEGER := 0;
    bounded_radius DOUBLE PRECISION;
    notification_type TEXT;
    caller_is_service BOOLEAN := auth.role() = 'service_role';
BEGIN
    IF sender_user_id IS NULL
       OR p_alert_type IS NULL
       OR lat IS NULL OR lat NOT BETWEEN -90 AND 90
       OR lon IS NULL OR lon NOT BETWEEN -180 AND 180
       OR radius_nm IS NULL OR radius_nm NOT BETWEEN 0.1 AND 5
       OR p_title IS NULL OR char_length(p_title) NOT BETWEEN 1 AND 120
       OR p_body IS NULL OR char_length(p_body) NOT BETWEEN 1 AND 500
       OR jsonb_typeof(COALESCE(alert_data, '{}'::jsonb)) <> 'object' THEN
        RAISE EXCEPTION 'Invalid Guardian alert';
    END IF;

    IF NOT caller_is_service THEN
        IF auth.uid() IS NULL OR sender_user_id <> auth.uid() THEN
            RAISE EXCEPTION 'Authentication mismatch';
        END IF;
        IF p_alert_type NOT IN ('suspicious', 'weather_spike') THEN
            RAISE EXCEPTION 'This alert type may only be generated by the watchdog service';
        END IF;
        IF NOT EXISTS (
            SELECT 1
            FROM public.guardian_profiles AS profile
            WHERE profile.user_id = auth.uid()
              AND profile.armed IS TRUE
              AND profile.last_known_at > now() - interval '5 minutes'
        ) THEN
            RAISE EXCEPTION 'Arm Guardian with a recent position before broadcasting';
        END IF;
        IF NOT public.consume_edge_quota('guardian_broadcast', 3, 3600) THEN
            RAISE EXCEPTION 'Guardian broadcast rate limit exceeded';
        END IF;
    ELSIF p_alert_type NOT IN ('bolo', 'drag_warning', 'geofence_breach') THEN
        RAISE EXCEPTION 'Unsupported watchdog alert type';
    END IF;

    bounded_radius := LEAST(GREATEST(radius_nm, 0.1), 5);

    INSERT INTO public.guardian_alerts(
        alert_type,
        source_user_id,
        source_vessel_name,
        title,
        body,
        location,
        radius_nm,
        data
    )
    SELECT
        p_alert_type,
        sender_user_id,
        profile.vessel_name,
        left(p_title, 120),
        left(p_body, 500),
        ST_SetSRID(ST_MakePoint(lon, lat), 4326)::geography,
        bounded_radius,
        COALESCE(alert_data, '{}'::jsonb)
            - 'exact_location' - 'lat' - 'lon' - 'latitude' - 'longitude'
    FROM public.guardian_profiles AS profile
    WHERE profile.user_id = sender_user_id
      AND (caller_is_service OR profile.armed IS TRUE)
    RETURNING id INTO alert_id;

    IF alert_id IS NULL THEN
        RAISE EXCEPTION 'Armed Guardian profile required';
    END IF;

    notification_type := CASE p_alert_type
        WHEN 'weather_spike' THEN 'weather_alert'
        WHEN 'bolo' THEN 'bolo_alert'
        WHEN 'drag_warning' THEN 'drag_warning'
        WHEN 'geofence_breach' THEN 'geofence_alert'
        ELSE 'suspicious_alert'
    END;

    FOR recipient IN
        SELECT profile.user_id
        FROM public.guardian_profiles AS profile
        WHERE profile.user_id <> sender_user_id
          AND profile.armed IS TRUE
          AND profile.last_known_at > now() - interval '5 minutes'
          AND profile.last_known_lat IS NOT NULL
          AND profile.last_known_lon IS NOT NULL
          AND ST_DWithin(
              ST_SetSRID(
                  ST_MakePoint(profile.last_known_lon, profile.last_known_lat),
                  4326
              )::geography,
              ST_SetSRID(ST_MakePoint(lon, lat), 4326)::geography,
              bounded_radius * 1852
          )
        ORDER BY profile.user_id
        LIMIT 50
    LOOP
        INSERT INTO public.push_notification_queue(
            recipient_user_id,
            notification_type,
            title,
            body,
            data
        )
        VALUES (
            recipient.user_id,
            notification_type,
            left(p_title, 120),
            left(p_body, 500),
            jsonb_build_object('alert_id', alert_id, 'alert_type', p_alert_type)
        );
        notify_count := notify_count + 1;
    END LOOP;

    RETURN notify_count;
END;
$$;

REVOKE ALL ON FUNCTION public.broadcast_guardian_alert(
    UUID, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, TEXT, JSONB
) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.broadcast_guardian_alert(
    UUID, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, TEXT, JSONB
) TO authenticated, service_role;

NOTIFY pgrst, 'reload schema';
