-- Return the committed Guardian alert to its sender in the same RPC response.
-- A queued-neighbour count is not proof of delivery and is never a reason to
-- hide a sender's own report. Keep the existing INTEGER RPC for older apps.
-- This does not add self-pushes, disclose nearby alerts, or widen table RLS.

CREATE OR REPLACE FUNCTION public.broadcast_guardian_alert_with_receipt(
    sender_user_id UUID,
    p_alert_type TEXT,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    radius_nm DOUBLE PRECISION DEFAULT 5,
    p_title TEXT DEFAULT '',
    p_body TEXT DEFAULT '',
    alert_data JSONB DEFAULT '{}'::jsonb
)
RETURNS JSONB
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    alert_id UUID;
    recipient RECORD;
    notify_count INTEGER := 0;
    bounded_radius DOUBLE PRECISION;
    notification_type TEXT;
    caller_is_service BOOLEAN := auth.role() = 'service_role';
    saved_alert JSONB;
BEGIN
    IF sender_user_id IS NULL
       OR p_alert_type IS NULL
       OR lat IS NULL OR lat NOT BETWEEN -90 AND 90
       OR lon IS NULL OR lon NOT BETWEEN -180 AND 180
       OR radius_nm IS NULL OR radius_nm NOT BETWEEN 0.1 AND 5
       OR p_title IS NULL OR char_length(p_title) NOT BETWEEN 1 AND 120
       OR p_body IS NULL OR char_length(p_body) NOT BETWEEN 1 AND 500
       OR jsonb_typeof(COALESCE(alert_data, '{}'::jsonb)) <> 'object' THEN
        RAISE EXCEPTION 'Invalid Guardian alert';
    END IF;

    IF NOT caller_is_service THEN
        IF auth.uid() IS NULL OR sender_user_id <> auth.uid() THEN
            RAISE EXCEPTION 'Authentication mismatch';
        END IF;
        IF p_alert_type NOT IN ('suspicious', 'weather_spike') THEN
            RAISE EXCEPTION 'This alert type may only be generated by the watchdog service';
        END IF;
        IF NOT EXISTS (
            SELECT 1
            FROM public.guardian_profiles AS profile
            WHERE profile.user_id = auth.uid()
              AND profile.armed IS TRUE
              AND profile.last_known_at > now() - interval '5 minutes'
        ) THEN
            RAISE EXCEPTION 'Arm Guardian with a recent position before broadcasting';
        END IF;
        IF NOT public.consume_edge_quota('guardian_broadcast', 3, 3600) THEN
            RAISE EXCEPTION 'Guardian broadcast rate limit exceeded';
        END IF;
    ELSIF p_alert_type NOT IN ('bolo', 'drag_warning', 'geofence_breach') THEN
        RAISE EXCEPTION 'Unsupported watchdog alert type';
    END IF;

    bounded_radius := LEAST(GREATEST(radius_nm, 0.1), 5);

    INSERT INTO public.guardian_alerts(
        alert_type,
        source_user_id,
        source_vessel_name,
        title,
        body,
        location,
        radius_nm,
        data
    )
    SELECT
        p_alert_type,
        sender_user_id,
        profile.vessel_name,
        left(p_title, 120),
        left(p_body, 500),
        ST_SetSRID(ST_MakePoint(lon, lat), 4326)::geography,
        bounded_radius,
        COALESCE(alert_data, '{}'::jsonb)
            - 'exact_location' - 'lat' - 'lon' - 'latitude' - 'longitude' - 'sent_by_you'
    FROM public.guardian_profiles AS profile
    WHERE profile.user_id = sender_user_id
      AND (caller_is_service OR profile.armed IS TRUE)
    RETURNING id INTO alert_id;

    IF alert_id IS NULL THEN
        RAISE EXCEPTION 'Armed Guardian profile required';
    END IF;

    notification_type := CASE p_alert_type
        WHEN 'weather_spike' THEN 'weather_alert'
        WHEN 'bolo' THEN 'bolo_alert'
        WHEN 'drag_warning' THEN 'drag_warning'
        WHEN 'geofence_breach' THEN 'geofence_alert'
        ELSE 'suspicious_alert'
    END;

    FOR recipient IN
        SELECT profile.user_id
        FROM public.guardian_profiles AS profile
        WHERE profile.user_id <> sender_user_id
          AND profile.armed IS TRUE
          AND profile.last_known_at > now() - interval '5 minutes'
          AND profile.last_known_lat IS NOT NULL
          AND profile.last_known_lon IS NOT NULL
          AND ST_DWithin(
              ST_SetSRID(
                  ST_MakePoint(profile.last_known_lon, profile.last_known_lat),
                  4326
              )::geography,
              ST_SetSRID(ST_MakePoint(lon, lat), 4326)::geography,
              bounded_radius * 1852
          )
        ORDER BY profile.user_id
        LIMIT 50
    LOOP
        INSERT INTO public.push_notification_queue(
            recipient_user_id,
            notification_type,
            title,
            body,
            data
        )
        VALUES (
            recipient.user_id,
            notification_type,
            left(p_title, 120),
            left(p_body, 500),
            jsonb_build_object('alert_id', alert_id, 'alert_type', p_alert_type)
        );
        notify_count := notify_count + 1;
    END LOOP;

    -- Read the inserted server row: its ID, timestamp and vessel identity must
    -- not be synthesized by the app. The marker is relative to the caller,
    -- never a claim taken from alert_data or supplied by another skipper.
    SELECT jsonb_build_object(
        'id', ga.id,
        'alert_type', ga.alert_type,
        'source_vessel_name', ga.source_vessel_name,
        'title', ga.title,
        'body', ga.body,
        'lat', round(ST_Y(ga.location::geometry)::numeric, 3)::double precision,
        'lon', round(ST_X(ga.location::geometry)::numeric, 3)::double precision,
        'data', (COALESCE(ga.data, '{}'::jsonb)
            - 'exact_location' - 'lat' - 'lon' - 'latitude' - 'longitude' - 'sent_by_you')
            || jsonb_build_object('sent_by_you', COALESCE(ga.source_user_id = auth.uid(), false)),
        'created_at', ga.created_at
    )
    INTO saved_alert
    FROM public.guardian_alerts AS ga
    WHERE ga.id = alert_id;

    RETURN jsonb_build_object('notified', notify_count, 'alert', saved_alert);
END;
$$;

-- Compatibility for already-installed apps and service-role callers. Delegate
-- once so authorization, quota, insertion and fan-out have one implementation.
CREATE OR REPLACE FUNCTION public.broadcast_guardian_alert(
    sender_user_id UUID,
    p_alert_type TEXT,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    radius_nm DOUBLE PRECISION DEFAULT 5,
    p_title TEXT DEFAULT '',
    p_body TEXT DEFAULT '',
    alert_data JSONB DEFAULT '{}'::jsonb
)
RETURNS INTEGER
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
    RETURN (public.broadcast_guardian_alert_with_receipt(
        sender_user_id, p_alert_type, lat, lon, radius_nm, p_title, p_body, alert_data
    ) ->> 'notified')::integer;
END;
$$;

-- Personal report history is not proximity discovery. Keep it visible during
-- a stale GPS fix or after moving away. Only target alerts still depend on the
-- caller's own armed, recent position; unrelated nearby alerts remain private.
CREATE OR REPLACE FUNCTION public.guardian_alerts_nearby(
    radius_nm DOUBLE PRECISION DEFAULT 10,
    max_hours INTEGER DEFAULT 24
)
RETURNS TABLE (
    id UUID,
    alert_type TEXT,
    source_vessel_name TEXT,
    title TEXT,
    body TEXT,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    data JSONB,
    created_at TIMESTAMPTZ
)
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    caller_lat DOUBLE PRECISION;
    caller_lon DOUBLE PRECISION;
BEGIN
    IF auth.uid() IS NULL THEN
        RAISE EXCEPTION 'Authentication required';
    END IF;
    IF NOT public.consume_edge_quota('guardian_alerts', 180, 3600) THEN
        RAISE EXCEPTION 'Guardian alert feed rate limit exceeded';
    END IF;

    SELECT gp.last_known_lat, gp.last_known_lon
    INTO caller_lat, caller_lon
    FROM public.guardian_profiles AS gp
    WHERE gp.user_id = auth.uid()
      AND gp.armed IS TRUE
      AND gp.last_known_at > now() - interval '5 minutes';

    -- Qualify arguments: guardian_alerts.radius_nm otherwise makes the query
    -- ambiguous (SQLSTATE 42702), which prevents even the sender's feed loading.
    RETURN QUERY
    SELECT ga.id,
           ga.alert_type,
           ga.source_vessel_name,
           ga.title,
           ga.body,
           round(ST_Y(ga.location::geometry)::numeric, 3)::double precision,
           round(ST_X(ga.location::geometry)::numeric, 3)::double precision,
           (COALESCE(ga.data, '{}'::jsonb)
               - 'exact_location' - 'lat' - 'lon' - 'latitude' - 'longitude' - 'sent_by_you')
               || jsonb_build_object('sent_by_you', COALESCE(ga.source_user_id = auth.uid(), false)),
           ga.created_at
    FROM public.guardian_alerts AS ga
    WHERE ga.created_at > now() - make_interval(hours => LEAST(GREATEST(guardian_alerts_nearby.max_hours, 1), 24))
      AND (
          ga.source_user_id = auth.uid()
          OR (
              ga.target_user_id = auth.uid()
              AND caller_lat IS NOT NULL
              AND caller_lon IS NOT NULL
              AND ga.location IS NOT NULL
              AND ST_DWithin(
                  ga.location,
                  ST_SetSRID(ST_MakePoint(caller_lon, caller_lat), 4326)::geography,
                  LEAST(GREATEST(guardian_alerts_nearby.radius_nm, 0.1), 10) * 1852
              )
          )
      )
    ORDER BY ga.created_at DESC
    LIMIT 50;
END;
$$;

REVOKE ALL ON FUNCTION public.broadcast_guardian_alert_with_receipt(
    UUID, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, TEXT, JSONB
) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.broadcast_guardian_alert_with_receipt(
    UUID, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, TEXT, JSONB
) TO authenticated, service_role;

REVOKE ALL ON FUNCTION public.broadcast_guardian_alert(
    UUID, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, TEXT, JSONB
) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.broadcast_guardian_alert(
    UUID, TEXT, DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION, TEXT, TEXT, JSONB
) TO authenticated, service_role;

REVOKE ALL ON FUNCTION public.guardian_alerts_nearby(DOUBLE PRECISION, INTEGER) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.guardian_alerts_nearby(DOUBLE PRECISION, INTEGER) TO authenticated;

NOTIFY pgrst, 'reload schema';
