#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# Thalassa Pi Cache — One-Command Install
#
# Run this on your Raspberry Pi:
#   curl -sSL https://raw.githubusercontent.com/shanestratton/thalassa-marine-weather/master/pi-cache/install.sh | bash
#
# Or if you've already cloned the repo:
#   cd pi-cache && bash install.sh
#
# What this does:
#   1. Installs Node.js 20 if needed
#   2. Installs dependencies
#   3. Asks for your Supabase credentials (optional)
#   4. Asks for your cruising area (optional)
#   5. Creates a systemd service so it starts on boot
#   6. Starts the cache server
#
# That's it. Your phone will find it automatically.
# ═══════════════════════════════════════════════════════════════

set -e

BOLD='\033[1m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m' # No color

echo ""
echo -e "${CYAN}${BOLD}  🌊  Thalassa Pi Cache Installer${NC}"
echo -e "${CYAN}  ═══════════════════════════════════${NC}"
echo ""

# ── Check we're on a Pi (or at least Linux) ──

if [[ "$(uname)" != "Linux" ]]; then
    echo -e "${YELLOW}⚠️  This script is designed for Raspberry Pi (Linux).${NC}"
    echo -e "   Running on $(uname). Proceeding anyway...\n"
fi

# ── Find our install directory ──

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}" 2>/dev/null || echo ".")" && pwd)"
if [[ -f "$SCRIPT_DIR/package.json" ]]; then
    INSTALL_DIR="$SCRIPT_DIR"
else
    INSTALL_DIR="/opt/thalassa-pi-cache"
    echo -e "${CYAN}Installing to ${INSTALL_DIR}${NC}"

    # If running from curl | bash, clone or download
    if [[ ! -d "$INSTALL_DIR" ]]; then
        sudo mkdir -p "$INSTALL_DIR"
        sudo chown "$USER:$USER" "$INSTALL_DIR"

        if command -v git &>/dev/null; then
            echo "Cloning pi-cache from GitHub..."
            git clone --depth 1 --filter=blob:none --sparse \
                https://github.com/shanestratton/thalassa-marine-weather.git /tmp/thalassa-clone
            cd /tmp/thalassa-clone
            git sparse-checkout set pi-cache
            cp -r pi-cache/* "$INSTALL_DIR/"
            rm -rf /tmp/thalassa-clone
        else
            echo -e "${RED}❌ git not found. Install git first: sudo apt install git${NC}"
            exit 1
        fi
    fi
fi

cd "$INSTALL_DIR"
echo -e "${GREEN}✓${NC} Working directory: $INSTALL_DIR\n"

# ── Check / Install Node.js ──

if ! command -v node &>/dev/null; then
    echo -e "${CYAN}📦 Node.js not found. Installing Node.js 20...${NC}"
    curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
    sudo apt-get install -y nodejs
    echo -e "${GREEN}✓${NC} Node.js $(node -v) installed\n"
else
    NODE_VERSION=$(node -v)
    echo -e "${GREEN}✓${NC} Node.js $NODE_VERSION found"

    # Check minimum version (need 18+)
    MAJOR=$(echo "$NODE_VERSION" | sed 's/v//' | cut -d. -f1)
    if (( MAJOR < 18 )); then
        echo -e "${YELLOW}⚠️  Node.js 18+ recommended. You have $NODE_VERSION${NC}"
    fi
    echo ""
fi

# ── Install npm dependencies ──

echo -e "${CYAN}📦 Installing dependencies...${NC}"
npm install --production 2>&1 | tail -3
echo -e "${GREEN}✓${NC} Dependencies installed\n"

# ── Build TypeScript ──

echo -e "${CYAN}🔨 Building...${NC}"
npm run build 2>&1 | tail -3
echo -e "${GREEN}✓${NC} Built successfully\n"

# ── Create .env if it doesn't exist ──

if [[ ! -f ".env" ]]; then
    echo -e "${CYAN}${BOLD}⚙️  Quick Setup${NC}"
    echo -e "   (Press Enter to skip any question)\n"

    # Supabase
    echo -e "${BOLD}Your Supabase project URL:${NC}"
    echo -e "   (Find this at supabase.com → your project → Settings → API)"
    read -r -p "   URL: " SUPA_URL
    echo ""

    echo -e "${BOLD}Your Supabase anon key:${NC}"
    read -r -p "   Key: " SUPA_KEY
    echo ""

    # Pre-fetch location
    echo -e "${BOLD}Where do you normally sail?${NC}"
    echo -e "   Enter latitude and longitude for pre-fetch"
    echo -e "   (e.g., Auckland: -36.84, 174.76)"
    read -r -p "   Latitude:  " PF_LAT
    read -r -p "   Longitude: " PF_LON
    echo ""

    # Defaults
    SUPA_URL="${SUPA_URL:-https://YOUR_PROJECT.supabase.co}"
    SUPA_KEY="${SUPA_KEY:-your-anon-key-here}"
    PF_LAT="${PF_LAT:--36.84}"
    PF_LON="${PF_LON:-174.76}"

    cat > .env <<ENVEOF
# Thalassa Pi Cache — generated by install.sh
PORT=3001
SUPABASE_URL=$SUPA_URL
SUPABASE_ANON_KEY=$SUPA_KEY
CACHE_DIR=./cache
PREFETCH_INTERVAL=15
PREFETCH_LAT=$PF_LAT
PREFETCH_LON=$PF_LON
PREFETCH_RADIUS=5
ENVEOF

    echo -e "${GREEN}✓${NC} Created .env\n"
else
    echo -e "${GREEN}✓${NC} .env already exists (keeping your config)\n"
fi

# ── Create systemd service ──

echo -e "${CYAN}🔧 Setting up systemd service...${NC}"

SERVICE_FILE="/etc/systemd/system/thalassa-cache.service"

sudo tee "$SERVICE_FILE" > /dev/null <<SVCEOF
[Unit]
Description=Thalassa Pi Cache — Local weather/tide/GRIB proxy
Documentation=https://github.com/shanestratton/thalassa-marine-weather
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$INSTALL_DIR
ExecStart=/usr/bin/node dist/server.js
Restart=always
RestartSec=10
Environment=NODE_ENV=production

# Performance — let it use decent resources
Nice=-5
LimitNOFILE=65535

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=thalassa-cache

[Install]
WantedBy=multi-user.target
SVCEOF

sudo systemctl daemon-reload
sudo systemctl enable thalassa-cache
echo -e "${GREEN}✓${NC} systemd service created and enabled\n"

# ── Start the service ──

echo -e "${CYAN}🚀 Starting Thalassa Pi Cache...${NC}"
sudo systemctl start thalassa-cache
sleep 2

if sudo systemctl is-active --quiet thalassa-cache; then
    echo -e "${GREEN}✓${NC} Service is running!\n"
else
    echo -e "${RED}❌ Service failed to start. Check logs:${NC}"
    echo -e "   sudo journalctl -u thalassa-cache -f\n"
    exit 1
fi

# ── Get the Pi's IP address ──

PI_IP=$(hostname -I | awk '{print $1}')
PI_HOSTNAME=$(hostname)

echo ""
echo -e "${GREEN}${BOLD}  ═══════════════════════════════════════════════${NC}"
echo -e "${GREEN}${BOLD}  🌊  Thalassa Pi Cache is ready!${NC}"
echo -e "${GREEN}${BOLD}  ═══════════════════════════════════════════════${NC}"
echo ""
echo -e "  Your Pi Cache is running at:"
echo -e "    ${CYAN}${BOLD}http://${PI_IP}:3001${NC}"
echo -e "    ${CYAN}http://${PI_HOSTNAME}.local:3001${NC}"
echo ""
echo -e "  ${BOLD}On your phone:${NC}"
echo -e "    Open Thalassa → Settings → Pi Cache"
echo -e "    It should find the Pi automatically!"
echo ""
echo -e "  ${BOLD}Useful commands:${NC}"
echo -e "    Check status:  ${CYAN}sudo systemctl status thalassa-cache${NC}"
echo -e "    View logs:     ${CYAN}sudo journalctl -u thalassa-cache -f${NC}"
echo -e "    Restart:       ${CYAN}sudo systemctl restart thalassa-cache${NC}"
echo -e "    Stop:          ${CYAN}sudo systemctl stop thalassa-cache${NC}"
echo ""
echo -e "  Fair winds! 🚢"
echo ""
