export enum RecordType {
    HEADER_SENC_VERSION = 1,
    HEADER_CELL_NAME = 2,
    HEADER_CELL_PUBLISHDATE = 3,
    HEADER_CELL_EDITION = 4,
    HEADER_CELL_UPDATEDATE = 5,
    HEADER_CELL_UPDATE = 6,
    HEADER_CELL_NATIVESCALE = 7,
    HEADER_CELL_SENCCREATEDATE = 8,
    HEADER_CELL_SOUNDINGDATUM = 9,

    FEATURE_ID_RECORD = 64,
    FEATURE_ATTRIBUTE_RECORD = 65,

    FEATURE_GEOMETRY_RECORD_POINT = 80,
    FEATURE_GEOMETRY_RECORD_LINE = 81,
    FEATURE_GEOMETRY_RECORD_AREA = 82,
    FEATURE_GEOMETRY_RECORD_MULTIPOINT = 83,
    FEATURE_GEOMETRY_RECORD_AREA_EXT = 84,

    VECTOR_EDGE_NODE_TABLE_EXT_RECORD = 85,
    VECTOR_CONNECTED_NODE_TABLE_EXT_RECORD = 86,
    VECTOR_EDGE_NODE_TABLE_RECORD = 96,
    VECTOR_CONNECTED_NODE_TABLE_RECORD = 97,

    CELL_COVR_RECORD = 98,
    CELL_NOCOVR_RECORD = 99,
    CELL_EXTENT_RECORD = 100,
    CELL_TXTDSC_INFO_FILE_RECORD = 101,

    SERVER_STATUS_RECORD = 200,
}

export function recordTypeName(type: number): string {
    return RecordType[type] ?? `UNKNOWN_${type}`;
}
